### ISSUE TITLE
EJSONinifcation of Astronomy documents

### ISSUE THREAD

**Issue by jagi** [jagi/meteor-astronomy#11]
This is the next feature I'm going to implement. This will allow sending Astronomy models as a param of Meteor method.

**Comment by dovrosenberg** [comment]
I'm having trouble with this... It's throwing an error when I try to pass an Astronomy object to the server in a Meteor method.

I've create this simple meteorpad to illustrate: http://meteorpad.com/pad/WncF7ajyC9zoP8Sqf/Astronomy%20Server%20Check

If you click the "add astronomy" button, it should add the new row to the view - you can see it flash up when it's created on the client; it then disappears because the server isn't saving the object.

The "old school" button is just there for comparison.

Am I doing something wrong?

Thanks - this has the makings of an amazing tool.... I'm hoping to replace Mesosphere, collection-hooks, collection-helpers, and a bunch of custom code - all with a cleaner code base!

**Comment by jagi** [comment]
Hi @dovrosenberg thanks for good words :)

I've downloaded code from meteorpad to my computer and run meteor application. At first I've received message on the console:

```sh
=> Started proxy.                             
=> Started MongoDB.                           
                                              
Changes to your project's package version selections:
                                              
jagi:astronomy  upgraded from 0.1.0 to 0.9.2  

=> Started your app.                          

=> App running at: http://localhost:3000/
```

It seems like in your packages file in the .meteor directory you have save old version of Astronomy.
However, when I run application, everything worked properly. Maybe try updating packages by force?

```sh
$ meteor update --packages-only
```

Or try editing packages file by hand.

Let me know if it helped.

**Comment by dovrosenberg** [comment]
Ah - sorry.  I had an issue in a more complex project I was trying to reproduce and the meteorpad versioning made me think I had it.  

I've updated the meteorpad - you'll still have to download it and meteor update to get it to run.  But then you'll see the problem.  It actually appears to be related to validation.

The validation is passing on the client, but not on the server.  The two buttons now do the same thing (i.e. call save() inside a Meteor method), but the first one only saves after checking validate().  You can see it flash still because it does successfully validate on the client, but not on the server...

Any ideas?

Thanks

**Comment by jagi** [comment]
Yep, now I see the problem. It appeared that I have error in EJSONification code. I was treating `values` as simple object instead stringifying it so that dates will be stored properly. I'm working on new version of validators and there it works. It should appear today on Atmosphere. So stay tuned :).

Thanks for noticing this error!

**Comment by jagi** [comment]
Ok I've fixed it in the newest version. Let me know if it works for you.

**Comment by dovrosenberg** [comment]
Thanks for the quick fix... upgraded main package and validators to 0.10.0 and now I get (when building that meteorpad code):

    TypeError: Object #<Object> has no method 'isDate'
    W20150531-12:32:32.292(-4)? (STDERR)     at app\common.js:11:25
    W20150531-12:32:32.292(-4)? (STDERR)     at app\common.js:26:3
    W20150531-12:32:32.293(-4)? (STDERR)     at h:\astro\.meteor\local\build\programs\server\boot.js:222:10
    W20150531-12:32:32.293(-4)? (STDERR)     at Array.forEach (native)
    W20150531-12:32:32.293(-4)? (STDERR)     at Function._.each._.forEach (C:\Users\Dov\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
    W20150531-12:32:32.293(-4)? (STDERR)     at h:\astro\.meteor\local\build\programs\server\boot.js:117:5

which is the line where the validator is attached...

Changing it to just date() makes everything work fine - did you get rid of the alias?

**Comment by jagi** [comment]
@dovrosenberg Yes I had to remove aliases. The reason for doing so is the ability to clearly determine what validator caused validation error. Before fix when you used `date` validator then in the `validationerror` event you received information that the validator that caused error is `isDate` which could be confusing. Now it's clear :). When version 1.0.0 will arrive, there won't be changes that are not backward compatible.
