### ISSUE TITLE
.get() returning self when no params

### ISSUE THREAD

**Issue by awei01** [jagi/meteor-astronomy#129]
Hi, just noticed this line: 
https://github.com/jagi/meteor-astronomy/blob/master/lib/modules/fields/get.js#L94

Wondering what the motivation for not returning an object w/ all the fields and their values?

**Comment by jagi** [comment]
It's intentional. Now the `raw` method dies exactly the same a previously `get`. And it's returning itself because nested fields has to be astronomy objects not plain JavaScript objects. The get method is used to get a value and the raw method to get a raw data. I know it's compatibility breaking but I've described it in change log.

**Comment by awei01** [comment]
Ok thanks for explanation.
