### ISSUE TITLE
Behaviors are not getting executed

### ISSUE THREAD

**Issue by katrotz** [jagi/meteor-astronomy#130]
I have defined a behavior (astronomy@1.1.0) but it does not get executed (`createSchemaDefinition` is never called).

The problem seems to be in the [storage module init definition](https://github.com/jagi/meteor-astronomy/blob/master/lib/modules/storage/init_definition.js).

It is registering an `initDefinition` event, creating a new schema definition object `extendDefinition` then extending the Class using this new object (dropping the schemaDefinition received from the arguments that has my behavior definition). 
Class extension method calls `initDefinition` event again, which I think might cause a **recursion**. 

I assume the line needs to be reviewed
```
// Extend the current schema definition.
Class.extend(extendDefinition);
```

**Comment by jagi** [comment]
You would have to show code of your behavior. Wrong usage of the `Class.extend` method can cause infinite recursion. The `storage` module avoids that in a little bit "hacky" way. The `createSchemaDefinition` method is called when you add a behavior to the class. Maybe that's why it's never get called in your case.

**Comment by katrotz** [comment]
You are right, I misspelled the `behaviors` using the singular form on the class definition. 
The issue can be closed.

**Comment by jagi** [comment]
Ok good to hear :)
