### ISSUE TITLE
Push/pull ReferenceError on nested Fields

### ISSUE THREAD

**Issue by Kyezil** [jagi/meteor-astronomy#131]
Push, pull calls to nested fields output`ReferenceError: fieldValue not defined`
Given this Class:
```javascript
Element = Astro.Class({
  name: 'test',
  fields: {
    properties: {
      type: 'object',
      nested: 'array',
      default: function() {
           return {prop:[]}
      }
    }
  }
});
```
`obj.push('properties.prop', 1)` and `obj.pull('properties.prop', 1)` throw the error (pull only if properties.prop is not empty)

Using version 1.1.0

**Comment by jagi** [comment]
You can use type of `array` in a `nested` property. The `nested` property value has to be the other class name or any other type but not `object` and `array`. I should actually prevent that by displaying an error in the console. Take a look [here](https://github.com/jagi/meteor-astronomy-examples/blob/flowrouter/both/collection.js#L77) how nested property is defined.

**Comment by Kyezil** [comment]
Thank you for your time. I really want to make extensive use of Astronomy.
Haven't had time to try it, but I will soon.

So, if I've understood correctly, it's impossible to have an object of arrays directly. I must have an object of Astro Classes which can have an array field. So push would be done with : `obj.push('properties.class.prop', 1)` or `obj.properties.class.push('prop', 1)` ?

**Comment by jagi** [comment]
You can have array of objects and object with a field of array type.

Having object of arrays is not event possible. Of course, you can treat object as an array in JS just by adding numerical keys but it won't behave as an array.

I think your problem is more about how to structure your data then how to use Astronomy.

```js
doc.push('nestedArrayField', 1);
doc.push('nestedObjectField.arrayField', 2);
```

In the listing above, you have examples of a correct usage of the `push` method. The class schema would look like follows:

```js
Item = Astro.Class({
  /* ... */
  fields: {
    nestedArrayField: {
      type: 'array',
      nested: 'number'
    },
    nestedObjectField: {
      type: 'object',
      nested: 'NestedClass'
    }
  }
});

NestedClass = Astro.Class({
  /* ... */
  fields: {
    arrayField: {
      type: 'array',
      nested: 'number'
    }
  }
});
```

**Comment by ianmartorell** [comment]
Hey @jagi, from your example it seems that setting `nested: 'NestedClass'` on a field of type `object` makes the field itself take the class `NestedClass`. As opposed to what happens with a field of type `array`, whose elements are the ones that take the class speficied by `nested`.

It seems weird to me that `nested` does different things depending on the type of the field... or am I missing something here?

**Comment by Kyezil** [comment]
I agree with @ianmartorell, I thought `nested` defined the type of contained elements (value of `array[i]` or `obj[prop]`. Now I see that the actual behaviour is implicit from the example (here and on the doc). Thank you.
What I meant by 'object of arrays' is, more precisely, an 'object which properties/fields are arrays'

I want to have a structure like a map (C++) or dictionary (Python) of arrays:
```C++
std::map<string, std::vector<string> >
```
```python
dict = {'string': [list of strings]}
```
Or what I expect in JS:
```javascript
{
    color: [ 'red', 'blue', 'green' ],
    size: ['small', 'medium', 'huge']
}
```
So that I can add properties (can do that with `set`) and add values to the arrays (my actual problem).
If I try `obj.push('color', 'yellow')` I get the `fieldValue` error, pushing directly to the array `obj.color.push('yellow')` works but Astro doesn't detect the change (`obj.isModified()` returns false).

Here come the questions:
1) Is it possible to model such a structure with Astronomy and define the type of the properties of an object (here arrays of Strings) ?
2) Can I use the push method of the class with these arrays ?
3) If not, how can I make Astronomy detect the change made with `array.push`

The only working solution I have now is a sequence of `get, push, set` on a field of an object of the Class

**Comment by jagi** [comment]
I has to be done that way because of backward compatibility with a beta version. I didn't want to make a revolution for users already using Astronomy in their projects. I had an idea for defining nesting in a little bit different way, maybe more logical but I had to meet halfway.

I'm planning to change it a little bit in the `relations` module for Astronomy but it won't appear this year. There will be a choice, but don't want to give more details now.

You can get accustomed to the current solution. It's not perfect but works.

If it goes about arrays. You have to know that right now an array object is just a simple JavaScript array object and using the `push` method on it doesn't give Astronomy any clue what to do with it. You shouldn't mess with data directly. Instead you should use methods provided in the astronomy class.

```js
doc.push('arrayField', 'value');
doc.pull('arrayField', 'anotherValue');
```

**Comment by ianmartorell** [comment]
So it's currently impossible to have a field of type `object` with properties of type `array` :cry:

**Comment by jagi** [comment]
It's possible. Please read a documentation about nesting fields. There are all information you need.

**Comment by ianmartorell** [comment]
No, it's not possible. The documentation speaks about defining the class of a field of type `object`, but not about defining the class of its properties. You should re-read [my comment](https://github.com/jagi/meteor-astronomy/issues/131#issuecomment-148935498) if you don't see the difference. What we're trying to achieve here is an object whose **properties** are arrays. Neither the documentation nor your examples provide any clue as to how to do this. Especially since `nested` defines the class of the actual field, not the class of it's properties, which would be the obvious behaviour given its name. 

If you still think it's possible, please provide an example or point us to the piece documentation that talks about how to do so.

**Comment by jagi** [comment]
Here is an example: https://github.com/jagi/meteor-astronomy-examples/blob/ironrouter/both/collection.js#L84

**Comment by ianmartorell** [comment]
No, that's a field of type `array` whose properties are objects of type `Phone`. We want a field of type `object` whose properties are of type `array`.

**Comment by jagi** [comment]
```js
NestedItem = Astro.Class({
  name: 'NestedItem',
  fields: {
    arrayField: {
      type: 'array',
      nested: 'number'
    },
    anotherArrayField: {
      type: 'array',
      nested: 'string'
    }
  }
});

Item = Astro.Class({
  name: 'Item',
  collection: Items,
  fields: {
    obj: {
      type: 'object',
      nested: 'NestedItem'
    }
  }
});

var i = new Item();
i.push('obj.arrayField', 2);
i.push('obj.anotherArrayField', 'str');
```

**Comment by ianmartorell** [comment]
Okay, I see where you're going. The problem with that implementation is that the array fields in `NestedItem` have to be declared beforehand. You lose the ability to dynamically add and remove properties to the object, which is what @Kyezil and I need, something like this:

```javascript
Item = Astro.Class({
  name: 'Item',
  collection: Items,
  fields: {
    obj: {
      type: 'object',
      default: function() {
        return {};
      }
    }
  }
});

var i = new Item();
i.set('obj.newArray', []);
i.push('obj.newArray', 'str'); // Throws ReferenceError
```

**Comment by jagi** [comment]
Ok it should work but I see that there is an error. I will fix it.

**Comment by ianmartorell** [comment]
Glad to hear that! Thanks :D

**Comment by jagi** [comment]
Ok I've fixed it but there is one requirement. You have to save a document between two operations on the same field. This is required by Mongo not by Astronomy. So your could will look like follows:

```js
var i = new Item();
i.set('obj.newArray', []);
i.save();
i.push('obj.newArray', 'str');
i.save();
```

Of course I could merge this two Mongo modifiers but it can produce unpredictable data. I will publish an update in a moment.

**Comment by ianmartorell** [comment]
That's fine with me :)

**Comment by jagi** [comment]
The new version is published 1.1.2, check it out.

**Comment by ianmartorell** [comment]
It works! :ok_hand:

**Comment by jagi** [comment]
Good to hear :). Closing this issue
