### ISSUE TITLE
Is it possible to use es2015 (aka es6) setters and getters for the models?

### ISSUE THREAD

**Issue by chaodoze** [jagi/meteor-astronomy#138]
So, in es6 we can do model.x = 'y' instead of model.set('x', 'y')

**Comment by jagi** [comment]
Hi, I've already answered this question a few times. It's not possible but I would like to and I used to.

1. In beta version it worked with ES6 setters and getters. However, in 1.0 I've decided to turn it off because it caused many problems and it's not available in older browsers.
2. It's not possible to polyfill it. Even Meteor 1.2 with Babel.js does not provide this feature for all browsers (of course I'm talking about IE). MDG does not recommend using setters/getters.
3. Using setters and getter causes many problems. Some packages are using `_.has(doc, '_id')` which does not detect setters/getters. And these packages may not work because of that, even Meteor does such checks very often.

I really would like to use setters/getters but as you can see, I can't. The biggest obstacle is point 3. I could just not support old browsers.

**Comment by chaodoze** [comment]
Thanks for your quick reply and apologies for not looking through past
issues. Very much liking the package from a day of tinkering!

**Comment by jagi** [comment]
No problem :). I should probably add FAQ section :). Enjoy :)
