### ISSUE TITLE
Server side global events?

### ISSUE THREAD

**Issue by gitamiller** [jagi/meteor-astronomy#142]
I'm new to meteor and astronomy so I apologize in advance if this is user error.

I'm trying to catch an astronomy event only on the server side but I can't seem to catch the event.

In /server/events.js I have the following:

Astro.eventManager.on('afterInsert', function(e) {
  console.log('Caught event');
});

The event is never logged in the console on the server. 

Is this by design or an error in astronomy?

**Comment by mariorodriguespt** [comment]
I have the same issue.

Astronomy relies on server Methods, you can also try it with `meteor shell`.

According to @jagi , the intended approach is to use methods.

**Comment by jagi** [comment]
How do you insert a document? You have to use `doc.save()` method not `Collection.insert()`. If you use `doc.save()` on the server then the `afterInsert` event handler will be called.

**Comment by gitamiller** [comment]
This was my error. I was using the insecure package and was creating the model and saving on the client.

It appears the event subsystems are completely separate on the client and server and the event is not being passed over the websocket. 

Once I removed insecure and added a method, I was able to do a few things:

* If the method was only on the server, the event was only on the server
* If the method was on both, I could see the event in both places.

Thanks.

If I may ask just one more question as I didn't see it in the documentation. On an insert, what's the difference between afterInsert and afterSave?

**Comment by jagi** [comment]
Events have to be run in both environments. You can never trust the client, so you have to repeat an event execution on the server. That's why it works that way.

The difference between `afterInsert` and `afterUpdate` is that the first on is called when you execute the `save` method on the newly created document and the second one when you execute it on a document already stored in a collection.

Closing this issue for now
