### ISSUE TITLE
Event name formatting?

### ISSUE THREAD

**Issue by rclai** [jagi/meteor-astronomy#16]
Is there a reason you made them lower case?

https://github.com/jagi/meteor-astronomy/#field-events

__Edit__: maybe even use dots?

`'after.set'`

**Comment by jagi** [comment]
In fact it does not matter what case you will use. Internally everything is lower case.
However if you take a look at the w3c standard, all events should be written lower case. You have `window.onclick` not `window.onClick`. But because of many styles of programming I'm allowing both. However I want to be compatible with the standard so I'm using lower case form in the documentation.

**Comment by jagi** [comment]
@rclai I see that you've made package for document methods. Right now I'm working on query builder for Astronomy, maybe would you like to help with that?

**Comment by rclai** [comment]
Sure, that sounds cool.

**Comment by rclai** [comment]
Just let me know how you want me to contribute logistically.

**Comment by jagi** [comment]
I've just started working on it https://github.com/jagi/meteor-astronomy-query-builder. At first I would like to discuss how it should look like, what functions it should have. Right now I thought about something like this:

```js
User = Astronomy.Class({
  collection: Users
  /* other attributes */
});

// In this place qb has collection already assigned to it and is stored in the "qr.collection" property.
var qb = User.createQueryBuilder();

// Add some selector.
qb.select({
  fieldName: 'test'
});

qb.options({
  sort: {
    fieldName: 1
  }
});
// or maybe...
qb.sort({
  fieldName: 1
}); // This approach seems to be easier.

qb.findOne(); // Returns single document.

qb.find(); // Returns cursor.
```

If you have any ideas how to improve it I would be glad. What use cases should I take into account.
And of course if you have any ideas you could create pull request.

I'm trying to take all the problems that developer may have and create complete packages list that will solve almost all of these problems.

**Comment by rclai** [comment]
Ah nice, I was about to suggest chaining, but you caught on :smile: :+1:.

**Comment by jagi** [comment]
Hehe :). I was working on it today a little bit. It appears that there are a lot of functions to implement. I'm not sure if I've taken a good approach trying wrap all mongo selectors, modifiers and options. I don't know how many of them are implemented in MiniMongo and if all of them needs some kind of wrapper. I will create some documentation to better show how it works right now.

**Comment by rclai** [comment]
The ones that I've created on my package you can use to wrap around the `modify` method.

**Comment by jagi** [comment]
Yes I will implement all of defined in your package and wait for any suggestion from the community. Maybe there is no need to create wrapper for every possible feature.

**Comment by VladShcherbin** [comment]
@jagi Hi, what is the reason for query builder? Isn't existing mongo functionality enough, maybe some use cases?

**Comment by jagi** [comment]
@VladShcherbin You won't be using it very often. But it may help in some situations. Let's say you have softremove behavior added to the class. The softremove behavior instead deleting document, sets the `removed` flag to `true` on the document to indicate that it had been removed. Without query builder you would do fetch all records as follows:

```js
Post = Astro.Class({
  /* ...*.
  behaviors: ['softremove']
});

Posts.find({
  removed: false
});
// or like that if you want to be sure that all records had been found
Posts.find({
  $or: [{
    removed: {
      $exists: false
    }, {
      removed: {
        $ne: true
      }
    }
});
```

With query builder you do:

```js
var qb = Post.createQueryBuilder();
qb.find();
```

Ok so that's one use case. You can also reuse a query builder.

```js
var qb = Post.creteQueryBuilder();
qb.selector({
  commentsCount: 10
});

var posts1 = qb.find(); // Take document with comments count equal 10

qb.sort('name', 1);
var posts2 = qb.find();  // Take document with comments count equal 10 and sort by name in ascending order
```

You can also create query builder not related with any class.

```js
var qb = new Astro.QueryBuilder();
qb.from(Collection);
qb.selector(/* ... */);
var doc = qb.findOne();
```

So it's why it's needed :)

**Comment by VladShcherbin** [comment]
@jagi oh, thanks for examples. Yep, I know what a query builder for :)

I guess, that we can't add smth to query: `Posts.find();`, so we need a builder, that does this. So with softDeletes we would need to change all *finds* to query builder to make *removed* automatically. Am I right ?

**Comment by jagi** [comment]
There are pros and cons of such approach. The one big advantage is no need for using any extra tools.

And here is a list of problems if we would like to wrap find and other functions:
- We shouldn't mess with those functions because we can break something :-P
- How would we resolve problem of finding all documents not only with soft removed flag? Some kind of option as the last parameter or on the level of a collection?
- We would have to implement mechanism of communication between Class and Collection so that every Collection would know what Classes are connected to it.

Personally I'm big fan of such approach. The best possible solution would be an ability to add some events to collection. It would be nice to have it done by Meteor team not by some package. So we could hook into collection methods.

Maybe we could do both. Query builder is in fact a nice way of reusing query. It requires less code to achieve the same thing.

**Comment by VladShcherbin** [comment]
@jagi yep, there is a package to do this, maybe you know it: [this one](https://github.com/matb33/meteor-collection-hooks)

I've used it before and it worked well indeed, there are also some methods for such kind of things: .before.find / .after.find.

Maybe it will you give you some thoughts or ideas ;)

**Comment by jagi** [comment]
Yes, I've heard about that one. It looks promising. However I would have to make something that works closely with Astronomy events system, so that any module, behavior could use hooks. I think I will create package for this. So there will be two ways of doing what we've talked about. One way will be using query builder and the second one using standard collection methods.

Right now I'm working on validators improvement. Simple validators works as I've told and I will release new version soon :). I have to make few more improvements.

**Comment by VladShcherbin** [comment]
@jagi oh, sure, with all you've done, I strongly believe in you and your decisions. I really hope you'll have enough power & time to finish all the packages, including astronomy, validators, query builder, forms, and everything coming in your head ;)

**Comment by jagi** [comment]
@VladShcherbin Thanks :). I have time and power but of course as always day is to short to make everything I would like to do :). I'm almost there, everything is going in the good direction :)

**Comment by jagi** [comment]
@VladShcherbin I've made two big changes nested fields' validators https://github.com/jagi/meteor-astronomy/wiki/Validators and a new way of defining simple validators https://github.com/jagi/meteor-astronomy/wiki/Simple-Validators.

**Comment by dandv** [comment]
"the w3c standard" may be all-lowercase, but the Meteor standard is camelCase:

* this.[onStop](http://docs.meteor.com/#/full/publish_onstop)
* Meteor.[onConnection](http://docs.meteor.com/#/full/meteor_onconnection)
* Accounts.[onCreateUser](http://docs.meteor.com/#/full/accounts_oncreateuser)
* Template.[onRendered](http://docs.meteor.com/#/full/template_onRendered)

etc.

I'd suggest recommending either the Meteor style in the README, or the [collection-hooks](https://github.com/matb33/meteor-collection-hooks#getting-started) dot-notation for those familiar with that package.

**Comment by jagi** [comment]
I don't understand why Meteor team haven't decided to use lowercase form or just implement simple events system as I've made for Astronomy https://github.com/jagi/meteor-astronomy/blob/master/lib/core/events.js. Thanks to that you could just write `Meteor.on('connection')` instead `Meteor.onConnection`. Their events only allow one event handler (listener) per event so maybe it's why they haven't decided to implement events manager.

Beside that I still don't know what notation I should follow so I've decided to support both. For me it's obvious that I should follow official standard.

One more thing is that they don't call it **event**. They call it **callback function**:

> Call inside the publish function. Registers a callback function to run when the subscription is stopped.

So maybe for that cases I should you camelCase format.

I know that camelCase format is easily readable. Maybe I will ask Meteor team what format, the developers should follow in that case.

**Comment by wursttheke** [comment]
Hi @jagi! I also feel the name 'events' is a little misleading. I would call them 'hooks' as in collection-hooks. Although technically the same, it is not really emitting events. It's more of a possibility to hook into the lifecycle of a documents or a collection.

**Comment by rclai** [comment]
I was trying to find the spec in w3c about lower case event names and could not find it. I also tried validating it using the w3c validator and they allowed both cases.

**Comment by jagi** [comment]
Yes naming it `hooks` is maybe a better idea. I was actually named `hooks` in the first version (in 2013) https://github.com/jagi/verin-model#hooks :). However isn't `onclick` event kinda of `hook` into the process of a mouse click? :) I think it can be used interchangeably with `event`, so I can allow both. Moreover developers can create their own events / hooks so it does not have to be hook.

**Comment by wursttheke** [comment]
Don't try to create too many API choices. You will have to support them for a long time and people will get confused in examples, tutorials and questions. Make a wise decision and keep the API simple. ;)

**Comment by jagi** [comment]
@wursttheke you may be right :). I will make that decision before 1.0.0 release :)

**Comment by ianserlin** [comment]
Just two-cents for posterity: We try to limit relying on `"literal strings"` as much as possible in because during the dev cycle it's much easier to get an `typoMethod is not a function` error in the console and fix it immediately then (usually silently) have nothing happen at all when you inevitably write typos.
