### ISSUE TITLE
Question about afterInit and afterChange multiple calls

### ISSUE THREAD

**Issue by dbismut** [jagi/meteor-astronomy#185]
Hi - I just wanted to know if it was normal behavior that just a `User.findOne()` call in the console from your meteor-astronomy-examples-flowrouter results in 11 `afterChange` calls and 1 `afterInit` call. Incidentally the `calculateAge` method is called twice.

![Chrome Console](http://i.imgur.com/LHEtQFa.png)

Also, does that mean that everytime I used `{{currentUser}}` the whole user object is initialized and `afterInit` called?

**Comment by jagi** [comment]
On a document initialization, the whole object is filled up with values so it has to set each individual field, so yes it's normal behavior. If it goes about the `calculateAge` method I could remove it's usage from the `afterInit` event because it's already called once after changing value of the `birthDate` field.

I don't know exactl how the `{{currentUser}}` is working internally, but my assumption is that it fetches current user from the database, so the Astronomy document needs to be initialized. If you are planning to use the {{currentUser}}` more than once it maybe good idea to store it in some variable.

**Comment by dbismut** [comment]
Clear. Thanks!

**Comment by ayalpani** [comment]
Hi. Another question regarding this same issue: when I repeat the same findOne **every** time, multiple afterChange calls do happen. So then, how is "document initialization" defined?

**Comment by jagi** [comment]
On document initialisation every document field is set which invokes `set` and `change` events. What was probably a bad idea but I had to make this compromise to allow behaviors manipulate data on document initialisation. However, in Astronomy 2.0 there is no `set` events and the `change` event is called only on document save instead of document change.
