### ISSUE TITLE
new class({params}) doesn't set nested fields or arrays

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#191]
The following works fine:
````
var client = new user({
            username: username,
            score: 5,
        });
        client.set({
            'profile.trainer': trainerId,
            'profile.firstName': first,
            'profile.lastName': last
        });
        client.push('emails', {address: email, verified: false});
````

But this does not:
````
var client = new user({
            username: username,
            score: 5,
            'profile.trainer': trainerId,
            'profile.firstName': first,
            'profile.lastName': last,
            'emails.0.address': email,
            'emails.0.verified': false
});
````

Neither the array nor the nested fields work (only single-depth fields seem to work), but they're fine if I put them in their own set and push functions.

**Comment by jagi** [comment]
You can't use such syntax in a document constructor, however you can use the `set` method:

Change this:

```js
var client = new user({
  'username': username,
  'score': 5,
  'profile.trainer': trainerId,
  'profile.firstName': first,
  'profile.lastName': last,
  'emails.0.address': email,
  'emails.0.verified': false
});
```

to this:

```js
var client = new user();
client.set({
  'username': username,
  'score': 5,
  'profile.trainer': trainerId,
  'profile.firstName': first,
  'profile.lastName': last,
  'emails.0.address': email,
  'emails.0.verified': false
});
```

and it should work well

**Comment by JulianKingman** [comment]
Cool, thanks.

**Comment by minfawang** [comment]
@jagi Looks like your code above doesn't work either. Not sure if this is expected behavior or not. 

So for example in the first situation:
~~~javascript
var client = new user();
client.set({
  'emails.0.address': email,
  'emails.0.verified': false
});
~~~
Then `client.email` will still be empty.

However, this code below will work:
~~~javascript
var client = new user();
client.set({
  'emails.0': {
    'address': email,
    'verified': false,
  }
});
~~~
It will result in `emails` array with length 1.

**Comment by jagi** [comment]
@minfawang are you sure that `emails` field's default value is set to empty array `[]` in the class schema? If not then it will not create array for you.

**Comment by minfawang** [comment]
@jagi Yes. In the scheme I set the default value for the array ( a function that returns an empty array). And using the first way to set value I got an array with length 0 rather than null or undefined.

**Comment by minfawang** [comment]
Here is the test schema definition that I use:

~~~javascript
Cls = Astro.Class({
  name: 'Cls',
  fields: {
    array: {
      type: 'array',
      default() { return [] },
      nested: {
        name: 'Object',
        fields: {
          field0: 'string',
          field1: 'number',
        }
      }
    },
  }
});
~~~

Below is a screenshot from the console.

![image](https://cloud.githubusercontent.com/assets/8814693/12540411/99aa2ac0-c2bd-11e5-83ae-28e80fe8d338.png)

**Comment by jagi** [comment]
That's because the `0` index does not exist and Astronomy does not create one for you. You have explicitly create new array elements.

**Comment by minfawang** [comment]
@jagi Yeah I understand the reason why the first way results in an empty array, but just want to make sure this is the expected behavior, because this results is different from the explanation of [your snippet](https://github.com/jagi/meteor-astronomy/issues/191#issuecomment-157327379) above. 

Probably the snippet just skips some details :)
