### ISSUE TITLE
ability to cancel database operations from events - question or feature request

### ISSUE THREAD

**Issue by dovrosenberg** [jagi/meteor-astronomy#20]
Is there a way that from inside a beforeSave/Insert/Update/Remove event we can cause the database operation to be canceled?  For example, this would enable the soft delete functionality you've shown to apply to actual removes vs. having to call a special function.

**Comment by jagi** [comment]
Yes, we've talked about that possibility. It could be good to have a choice and I didn't say know :). If there is a need for such feature then I will implement it. It's a matter of a few lines of code. I will extend `Astro.Event` object and call it `Astro.StoreEvent` (or something like this). This event will have additional method:

```js
onsave: function(e) {
  e.stopOperation();
}
```

Or any name that is descriptive enough.
Adding it to the list of thing to do.

**Comment by jagi** [comment]
Ok I've added such feature. Now you can do as follows:

```js
events: {
  beforesave: function(e) {
    e.preventDefault();
  }
}
```

It will stop default operation like `save`, `remove` however it won't stop event propagation. If you want both. Just type:

```js
events: {
  beforesave: function(e) {
    e.preventDefault();
    e.stopPropagation();
  }
}
```

However, I'm not planning to change that in the `softremove` behavior right now. Because we've already talked that it would be better to have separate function for soft removing. However we can talk about it one more time :)

**Comment by dovrosenberg** [comment]
Awesome.  I think it makes sense to leave the softremove, as well, as there are clearly use cases where that approach is preferred.  But with the change you made, people (like me) can now create their own behavior if they want.

     - Dov

**Comment by jagi** [comment]
Great :)
