### ISSUE TITLE
Inheritance does not work in nested fields

### ISSUE THREAD

**Issue by zvictor** [jagi/meteor-astronomy#205]
From the Inheritance section in the docs:
> When fetching the given document from the collection, the transform function will automatically fetch an instance of proper class.

This is true, but not when the document is nested. In that case, there is not magic transforming the instance to the proper class.

I have isolated the problem here: [zvictor/astronomy-inheritance-bug](https://github.com/zvictor/astronomy-inheritance-bug)

**Comment by jagi** [comment]
It works. The `raw()` method returns plain javascript objects, so that's why you see plain object instead Astronomy class.

**Comment by zvictor** [comment]
Let's forget `raw()`. What a call to `Items.find().fetch()` should return?

Why does it change the value of `embedded.type`?

In the database it is saved as `Child`, after transformation type becomes `Parent`.
 
![screen shot 2015-11-30 at 11 58 01](https://cloud.githubusercontent.com/assets/181076/11469841/a5dc9a10-9759-11e5-8faa-e06ad90382ae.png)

<img width="423" alt="screen shot 2015-11-30 at 11 57 20" src="https://cloud.githubusercontent.com/assets/181076/11469888/e1747cfa-9759-11e5-8967-ddbcdb5a9418.png">

**Comment by jagi** [comment]
Because you should not store as nested fields instances of classes that have the `collection` property provided. In fact in 2.0 I will throw error on such assignment. The `afterInit` events is executed on each document of the class that has the `collection` property. This event handler checks if there is a `typeField` property for the class and it's casted to the proper type. But in your situation you used it as a nested field. And the nested field has priority, so it changes type to `Parent`.

**Comment by zvictor** [comment]
Okay, I didn't know about these distinctions.

Will the nested field type always have the priority over the `typeField`? I just got confused because you started pointing the problem to the `collection` definition.

**Comment by jagi** [comment]
Yes it will always have a priority. Are you trying to implement Nested Tree?
