### ISSUE TITLE
type validators and "required"

### ISSUE THREAD

**Issue by dovrosenberg** [jagi/meteor-astronomy#21]
Sorry for the flood of new issues... hopefully they're helpful.

The type validators (date, email, etc.) all appear to return false (invalid) if the field is blank.  To me, it's more intuitive that they'd return true in that case.  If I want to fail a blank field, I'd add the "required" validator.  But if it's not marked as "required", it should not be required. :)

Not sure what others think, though.

**Comment by jagi** [comment]
I can understand your point of view but I don't know if it's intuitive for other. Today I will post question on gitter to get more opinions :)

**Comment by jagi** [comment]
@dovrosenberg I was thinking about it and I don't know if it's good idea. Let's say we have the `null` value assigned to the field and there is a `string` validator created for that field. Is `null` a string? Definitely no.

But as I sad I can understand your point of view. You would probably like to have feature from relation databases called `NOT_NULL` field. By default any column can be null. So we can assign a value or left it empty. But when we set field as `NOT_NULL` then we have to assign non null value (fields is required). However this behavior is not related with validation. If you would like to achieve such behavior you would have to create following validation rule in Astronomy.

```js
validators: {
  'field': Validators.or([
    Validators.null(),
    Validators.and([
      Validators.required(),
      Validators.string(),
      Validators.minLength(5)
    ])
  ])
}
``

I know that it's not a very short rule but it would make more sense. Maybe it shouldn't be something related with the validation. Maybe, I should introduce `required` option in the field's definition along with type and default value. It could work as follows:
1. If field has `required` attribute set to `true` then perform validation.
2. If field has `required` attribute set to `false` or left empty then check if field's value is `null` or `undefined`. If it's `null` or `undefined` then do not perform validation. If it's any other value then perform validation.

What do you think about this?

**Comment by dovrosenberg** [comment]
Perhaps I've introduced something that will make it too complicated. :)  I do think of required as being similar to NOT NULL.

I don't think any non-null field type should be required.  For example, on my contact object - there are first and last name - both strings and required.  There's middle name - a string if it exists, but not required.  Then there's email - not required, but if it does exist it has to be a valid email.

To me, it would make sense as follows:

1) If a field has a type, then the only valid values for that field are null or a value of that type.  
2) If it is also required, then null is not acceptable either.  Strings are more complicated, because I would generally say an empty string is also not acceptable in a required field.
3) If a field doesn't have a type, then anything can be stored there, so long as it passes validation.

Then validation would ignore missing fields and only check the format of fields with a value.  Also, you generally shouldn't need to validate string types with Validators.string() - that should be handled automatically by the type being set.

**Comment by jagi** [comment]
But it's very important to solve this problem at this stage :). I've solved this problem in the newest version of Astronomy core and validators. It's not published yet because I want to discuss it here.

I solved it in following way (referring to your points):

**0) Field type is only for casting values. It always was that way.**
Maybe I haven't described it good enough in the documentation. If field has type:

```js
field: {
  firstName: 'string'
}
``` 
then such assignment will cast `123` to string and we will get `"123"`

```js
var user = new User();
user.set('firstName', 123);
user.firstName; // "123" not 123 number
```

**1) If value has type then it MUST have NOT NULL value but only when we're validating this field.**
Let's say we have the following class definition:

```js
field: {
  firstName: 'string'
},
validators: {
  firstName: [
    Validators.string(),
    Validators.minLength(3)
  ]
}
```

And we try to validate the following object:

```js
var u = new User();
u.set('firstName', null);
u.validate();
```

We will get the following error: `The "firstName" field's value has to be a string`

**2) We can also modify our class and add `required` validator:**

```js
field: {
  firstName: 'string'
},
validators: {
  firstName: [
    Validators.required(),
    Validators.string(),
    Validators.minLength(3)
  ]
}
```

And we will try to validate:

```js
var u = new User();
u.set('firstName', null);
u.validate();
```

It will get the error: `The "firstName" field's value is required`. It will also get the same error with empty string `""`:

```js
var u = new User();
u.set('firstName', '');
u.validate();
```

**3) AS YOU WROTE: If a field doesn't have a type, then anything can be stored there, so long as it passes validation AND FIELD'S VALUE IS NOT NULL**

```js
{
  firstName: null
},
validators: {
  firstName: []
}

/* ... */

var u = new User();
u.set('firstName', null);
u.validate(); // TRUE
```

or

```js
{
  firstName: null
},
validators: {
  firstName: [
    Validators.required(),
    Validators.string()
  ]
}

/* ... */

var u = new User();
u.set('firstName', null);
u.validate(); // TRUE
```

but

```js
{
  firstName: null
},
validators: {
  firstName: [
    Validators.required()
    Validators.string()
  ]
}

/* ... */

var u = new User();
u.set('firstName', 0);
u.validate(); // FALSE
```

**SUMMARY**
Maybe it's a little bit confusing but you just have to remember that:

**Having VALIDATORS DEFINED for a field**
- **When field HAS TYPE, then it IS REQUIRED**
  - **For NULL value it WILL VALIDATE field**
  - **For NON NULL value it WILL VALIDATE field**
- **When field DOES NOT HAVE TYPE, then it IS NOT REQUIRED**
  - **For NULL value it WILL NOT VALIDATE field**
  - **For NON NULL value it WILL VALIDATE field**

So:
HAS TYPE - WILL ALWAYS VALIDATE
DOES NOT HAVE TYPE - WILL VALIDATE FOR NON NULL VALUES

Would you be happy with such solution?

**Comment by dovrosenberg** [comment]
Some thoughts:

>1) If field has type then it MUST have NON NULL value but only when we're validating this field.
Let's say we have the following class definition:

This is counter-intuitive to me - particularly for non-string fields (which have the advantage of being able to be empty strings).  Does this mean that any optional field must be defined to have no type if you want to validate?  

Imagine a Number field rating that is optional.  If it does exist, it has to be between 1 and 100.  It is filled by the user from a form (i.e. input as a string).  My choices with your approach seem to be:

1. No type - in which case the developer has to handle the casting from string to number manually; I can, however, setup a validator for non-null values
2. Type as Number - get casting, but now if I create a validator to check that it's between 1 and 100, but I can no longer save null ratings... 

Or did I misunderstand?

Ideally, I think I would simply do:
 
    fields: {
      rating: 'Number'
    },
    validators: {
      rating: [
        Validators.lte(100),
        Validators.gte(1)
      ]
    }

And if it was required (i.e. null is not acceptable):

    fields: {
      rating: 'Number'
    },
    validators: {
      rating: [
        Validators.required(),
        Validators.lte(100),
        Validators.gte(1)
      ]
    }

**Comment by VladShcherbin** [comment]
My 2 cents:
- If the field **is required** - **validate** its type and value.
- If the field **is not required and has value** - **validate** its type and value,
- If the field **is not required and does not have value** - **do not validate** its type and value.

I also find it weird:

```js
fields: {
  firstName: 'string'
},
validators: {
  firstName: [
    Validators.string(),
    Validators.minLength(3)
  ]
}
```

We set the firstName as a string, then we call again Validators.string() to validate it as a string. DRY, where are you? :(

**Comment by jagi** [comment]
I've made decision to not implement this feature. I've been working today on validators and `and` and `or` validators are good enough to validate any complex rule.

I have to repeat myself one more time:
TYPE field in `fields` is not the validator. It's just information for the Astronomy to what type any assigned value should be casted.

When you write:

```js
user.set('firstName', 123);
```

then

```js
user.firstName; // prints string "123" NOT number 123
```

So it's why the `type` option exists. In fact it does not allow saving into this field any other value type then one that is defined,  but you have to use `set` function. If you just write:

```js
user.firstName = 123;
```

then

```js
user.firstName; // It's number 123
```

So this is why I had to introduce this feature. It has nothing to do with the validation. I will describe it in details today in few hours.

**Comment by jagi** [comment]
@dovrosenberg you will be able to assign null value to the field with type defined. I will describe how it will work soon. Stay tuned. It will be intuitive.

**Comment by VladShcherbin** [comment]
@jagi yep, I know for what the type is. It's okay, it only looks like doing things twice ;)

**Comment by dovrosenberg** [comment]
I agree, @jagi.  So long as you can assign null to a typed field, people (including me) can custom build validators to make it work however they want.

**Comment by jagi** [comment]
Ok [here](https://github.com/jagi/meteor-astronomy/wiki/Validators#nested-validators) is a short section about nested validators (AND and OR) and how to use them to create validators like: `null || (string && minLength(5))`.

And to be precise. Those validators works with every type of the field. You can set type of the field to `string`, `number` or left empty. It's doesn't matter. You can assign `null` to field of any type. Maybe it's a little different approach than the one you could see in relational databases but that's why it differs. You don't have NOT_NULL fields in MongoDB, so it doesn't make sense to mimic this behavior. SQL and MongoDB are two different worlds :).

For now I'm closing this issue. If you have any other concerns, ideas please submit new issue :).
Regards!
