### ISSUE TITLE
Maybe add a .toObject() on astronomy documents?

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#212]
I am trying to do something like this:

```js
Accounts.onCreateUser(function(options, user) {
  var astroUser = new User(user);
  astroUser.set({
    profile: options.profile
  });

  return astroUser.toObject();
});
```

I tried ```.plain()``` as well, but still got an error that its not defined. Do we have such a function? If not i think this is pretty basic. I would have just passed the astroUser variable but it would only take a plain object.

I would recommend having this function called as ```plain()``` and then alias the same in ```.toObject()```.

@jagi maybe this is less than 2 minutes of your time haha.

**Comment by talha-asad** [comment]
So for now, this is what i am getting by:

```js
Accounts.onCreateUser(function(options, user) {
  var astroUser = new User(user);
  astroUser.set({
    profile: options.profile
  });

  return astroUser.get()._original;
});

It works cause its a new object, but you need to get this in.

**Comment by jagi** [comment]
I'm trying to using naming convention that is compatible with W3C standards. Non of the names `plain()`, `toObject()`, `raw()` fits into this naming convention. It's not always possible to find good equivalent name. However, I was thinking about using the `valueOf()` method name. Which by definition is:

```
The valueOf() method returns the primitive value of the specified object.
```

And `valueOf` the plain JavaScript object is plain JavaScript object. And `valueOf` the `String("asd")` is the `"asd"` string.

**Comment by shadowRR** [comment]
I found `.raw()` to be quite clear on what it's doing. For me, it's really saying that with it, you're only gonna get the raw data, and nothing else, while `toObject()` can have multiple interpretations...

**Comment by jagi** [comment]
@shadowRR yes It think that too

**Comment by talha-asad** [comment]
@jagi, you raise a good point with ```valueOf```.
@shadowRR I don't have any issues with using ```.raw()``` just couldn't find it directly in the docs, don't know which i found out about it. I think if the docs have a page of the methods you get on a document object it would be easier to find these sort of functions. I just thought we could have a few aliases so it would be more easier for people to adopt this package.

I understand ```.toObject()``` is a bit vague in the sense of, which Object are we referring to here, but generally its assumed to be a plain object.

**Comment by shadowRR** [comment]
@talha-asad What do you mean by not finding it directly in the docs ? There is pretty much every standard methods you get in a class in the docs... Or maybe you're not going to the same place as me :

[Astronomy Docs](http://astronomy.jagi.io/what-is-astronomy)

**Comment by jagi** [comment]
@talha-asad I've used to think that providing several aliases is a good idea but I've received feedback from users that they don't like it. It caused confusion. "Which method should I use?", "Oh that's alias...", "It would be better just to force using one method name" etc. So I understand your point but as I said it may cause confusion.

Another very important thing is polluting a document instance. Right now we have quite a lot methods in a document instance and adding more of them can influence somebody's code. I've recently read about the problem of W3C with the `Array.prototype.contains` method. They couldn't introduce this method because many website are using some library that adds such method to the Array prototype. And adding such method by W3C would cause many websites to stop working. And they decided to change the name to `Array.prototype.includes`.

Right now in a document with only Astronomy code package added we have the following properties/methods (41):
```
_modifiers, _original, _isNew, save, remove, reload, copy, typeName, toJSONValue, _executeModifier, _addModifier, _clearModifiers, _hasModifier, _getModifier, _getModifiers, _removeModifier, _setDefault, _setOne, _setMany, set, _getOne, _getMany, get, _rawOne, _rawMany, _rawAll, raw, _pushOne, _pushMany, push, _popOne, _popMany, pop, _pullOne, _pullMany, pull, _incOne, _incMany, inc, getModified, isModified
```

Quite a lot. I'm planning to reduce this number to 20 or less in Astronomy 2.0:
```
_isNew, save, remove, reload, copy, typeName, toJSONValue, _setOne, _setMany, set, _getOne, _getMany, _getAll, get, _rawOne, _rawMany, _rawAll, raw, getModified, isModified
```

Think that better documentation is something that we need more right now. I will be working on it after 2.0 release. There is a lot of work that have to be done :)

**Comment by talha-asad** [comment]
@jagi Well explained. Thank you for putting in the time to clear this up. Love the work you have been doing. I hope to contribute to it someday, hopefully when i dive into the code. :+1:
