### ISSUE TITLE
Question: what does the required validator does exactly?

### ISSUE THREAD

**Issue by lsunsi** [jagi/meteor-astronomy#217]
Fields are required by default in a Astronomy Schema, right?
That's what the optional is for, allowing a field to be unset.

Ok, so what's the required validator about?

That is probably a stupid question, but I can't figure it out

**Comment by jagi** [comment]
Right, fields by default are required but you can change that using the `optional` attribute in the field's definition. I know that existence of the required validator can be confusing. But its job is just to display an error message during the validation.

It will be changed in Astronomy 2.0, there will be no need to register the `required` validator for the required fields. It will be added automatically.

**Comment by lsunsi** [comment]
@jagi 
Ok, cool. But wait.
If I don't set up the required validator, an unset not optional field passes the validate method?

**Comment by jagi** [comment]
Please remove unnecessary double negations from your questions (unset not optional) because I don't understand your question.

**Comment by lsunsi** [comment]
Edited comment.

**Comment by jagi** [comment]
Ok thanks. To answer your question:
Unfortunately if you don't add required validator it will work. It's used only during validation. If a field is optional and there are some validators for the fields and the field value is `null` then it will not perform validation on this field. That's it. It was bad design decision which will be fixed in 2.0. Validation will be coupled with the core Astronomy and validation will take place on every save. And there will be correct check of the required fields.

**Comment by lsunsi** [comment]
got it. Awesome man!

Do we have an ETA on version 2.0?
Really looking forward to it

**Comment by jagi** [comment]
I want to release RC version before the end of this year.

**Comment by lsunsi** [comment]
That is AWESOME
