### ISSUE TITLE
Do storage events obey permissions (allow/deny)?

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#220]
Didn't test this but just wanted to make sure before i start using them.

Also if i use the isServer and isClient block in the hook function, will it work?

**Comment by jagi** [comment]
If you call `doc.save()` or `Class.insert()` on the client it will use allow/deny rules however event will not be triggered on the server so if you set let's say `createdAt` field on the client, the date will be from the client not from the server. And because of that, data may be corrupt. I can't trust such calls. You should always use Astronomy 1.0 with Meteor methods. However it will change in Astronomy 2.0. It won't use allow/deny rules in core package. However, it will execute all the events on both client and server. There will be also `jagi:astronomy-collection` package that will do the same but using allow/deny rules.

**Comment by talha-asad** [comment]
@jagi i am guessing executing all events on both client and server is for latency compensation?

Why do you want to package the allow/deny rule thing seperately. I am sure you have a good reason. Can you share that.

I think it makes sense to go through allow/deny when on the client because that is what you can't trust. But if someone uses it for some other purposes besides just doing permission work than that could be a problem.

**Comment by jagi** [comment]
@talha-asad yes it's for latency compensation.

It will be a separate package because you don't need allow/deny rules when using Astronomy 2.0. You will be able to use validators to secure inserts/updates/removes. However, if you will want to use use allow/deny rules you still can. It's just a choice.

You can trust Astronomy 2.0 making inserts/updates/removes on the client because they will be executed also on the server. And if you have validators, then they won't let you do not allowed operations.

**Comment by talha-asad** [comment]
Can't wait for 2.0 now :+1:
