### ISSUE TITLE
save() callback doesn't return correct id

### ISSUE THREAD

**Issue by satyavh** [jagi/meteor-astronomy#222]
according to docs, the save() callback returns the doc's id:
```
user.save(function(err, id) {
});
```

however, it always seems to return `1`

**Comment by jagi** [comment]
It depends on situation. If it's saving a new doc it will return id if a doc is already saved and we are only updating then it will return number of modified documents.

**Comment by satyavh** [comment]
Aha, that explains. I think the doc should be more clear on this.

In case of update, it might be better to return an array of ids of updated docs. That way you know, if you update multiple docs at once, which were successful and which failed. Otherwise, if you update 4 docs, and save() returns 2, how do you know which ones failed?

**Comment by jagi** [comment]
Yes right but you don't get that information from MongoDB. However I could receive that information from Astronomy as I have to fetch document before updating. However I want it to be consistent with MongoDB. In real life example you won't be doing multiple updates very often and probably information about what document failed during update does not give you a lot information. What you would want to get is information what caused error but that's a subject for another talk :)

**Comment by satyavh** [comment]
> In real life example you won't be doing multiple updates very often and probably information about what document failed during update does not give you a lot information.

Then you might as well return the id of the updated doc instead of the number of docs updated :-)

Anyway, it's clear for me. Closing this

**Comment by jagi** [comment]
Hmm we will see how it's gonna look like in Astronomy 2.0. I'm not gonna change that behaviour in current release because of backward compatibility.

No problem!

**Comment by sebastianconcept** [comment]
@jagi you can be consistent with MongoDB for its own protocol (`astroInstance.update` and `astroInstance.insert`) but your intention to unify simplifying with `astroInstance.save` should also homogenize the answer. Otherwise why using `.save` if I'm forced to know if it's an update or an insert to interpret the answer? If that would be the case then I would want my code to be honest and explicit and do use `.update` and `.insert` instead and completely ignore that `.save` exists.

PS: thanks for Astronomy is a great piece of software!
