### ISSUE TITLE
pull and object keys order

### ISSUE THREAD

**Issue by matthieu60** [jagi/meteor-astronomy#226]
It looks like Astronomy modifies the keys order of the objects it fetches from mongo, to enforce an alphabetical order, which is great.

The problem is that the pull method uses $pullAll internally, and $pullAll is sensitive to key order.
So, if you fetch an object (that was not created with Astronomy and has another key order), when you try to pull it, this will do nothing (and fail silently) because keys orders do not match.

I suggest replacing {$pullAll: []} with {$pull: $or: []} to fix this...

**Comment by jagi** [comment]
Astronomy does not mess with keys order. In fact it's not possible in JS. It depends on the browser. In Chrome it's alphabetical order but in other browsers may not be. Is JS spec you can read that you should not assume that order is alphabetical because it may vary from browser to browser.

**Comment by matthieu60** [comment]
Thanks for the answer. I was wrong on the "Astro changes keys order" part.
I do not assume anything about key order in my code, but mongo does sometimes, for instance when using the $pullAll operator... 
If browsers mess with that, that would be good reason to avoid this operator.

**Comment by jagi** [comment]
It's probably because of caring about fields order by MongoDB. You probably have to provide the same order as the originally saved document had. If you've used Astronomy to insert document then it would also work with pull operation.

You can just use direct collection access if you want to pull some value as it (probably) does not require any validation checks `Collection.update(selector, {$pull: { /* ... */ }});`
