### ISSUE TITLE
Collection.push(): Don't act as expected in mongo 

### ISSUE THREAD

**Issue by NaderIkladious** [jagi/meteor-astronomy#233]
When I try to push as I would do in Mongo if the field is not there it's automatically created
```javascript
      var user = User.findOne();
      var memberId = '123',
            postId = '321';
      user.push(`profile.members.${memberId}`, postId);
      user.save();
```
So instead of doing it like above, I have to do it this way.
```javascript
      var user = User.findOne();
      var memberId = '123',
            postId = '321';
      if( memberId in user.get('profile.members')) {
        user.push(`profile.members.${memberId}`, postId);
      } else {
        user.set(`profile.members.${memberId}`, [postId]);
      }
      user.save();
```

It would be a great enhancement if it have this logic happens behind the scene.

Mongo Behaviour: (Mongo Documentation)
```If the field is absent in the document to update, $push adds the array field with the value as its element.```

Thanks so much for your hard work,
Nader Ikladious.

**Comment by jagi** [comment]
Hi, I know about that limitation. It was already solved in Astronomy 2.0 and I'm not going to implement it in 1.0 because it has different system of document modifications and it would be hard to do all the changes. Astronomy 2.0 does changes the same way as MiniMongo. So if some feature is present in MiniMongo it's also available in Astronomy 2.0. If it goes about the release of 2.0. I've already wrote in a few issues that RC version will be available before the end of the year. But it will be probably the beginning of 2016 because there a few things to do.

**Comment by NaderIkladious** [comment]
Thanks so much, I am currently working on a project that is not released yet and looking forward to migrate to Astronomy 2.0.

**Comment by jagi** [comment]
I'm closing this issue for now. The RC version is available and you can test it out. It's quite stable now.
