### ISSUE TITLE
Validated update operation?

### ISSUE THREAD

**Issue by ayalpani** [jagi/meteor-astronomy#250]
Hi @jagi, 

when using `Class.update()` (see http://astronomy.jagi.io/direct-collection-access), how do I make sure all updated docs are validated correctly, as configured?

Example query:

```AstroItem.update({color: 'green'}, {$set: {color: 'blue'}}, {multi: true})```

Where `AstroItem` is an astronomy class, linked to an `Items` collection. The above query does not validate by default.

Must I first `find().fetch()` all matching docs, then `set()`, then `validate()`, then `save()`?

Cheers!

**Comment by jagi** [comment]
Unfortunately "direct collection access" in 1.0 is limited and you have to perform set, validate and save for each individual document after fetching. In 2.0 it will be done automatically.

**Comment by ayalpani** [comment]
Great to hear, the feature list looks promising! Any estimation when it will be available? :)

**Comment by jagi** [comment]
I'm doing my best to release it as soon as possible. Time is passing so fast :). I wanted to release RC version until the end of the year but unfortunately because of Christmas time and some personal stuff I wasn't able to work on it as much as I wanted. So, I don't want to provide any date and later don't meet the goal :). It will be definitely the first quarter of 2016. Maybe beginning of February but we will see :). Just follow the Astronomy 2.0 issue on GitHub to see what is the progress :)

**Comment by ayalpani** [comment]
I will, thanks!
