### ISSUE TITLE
Astronomy 2 - GraphQL support

### ISSUE THREAD

**Issue by zimt28** [jagi/meteor-astronomy#252]
Hey there!
I just came across Astronomy and it looks like you're about to release a version 2 soon.
I'm wondering if you've thought about GraphQL support? I know it's possible to convert mongoose schemas into GraphQL schemas, so why not do it with Astronomy as well?
Arunoda has just released a first GraphQL implementation for Meteor, so Astronomy might be a good fit.

What do you think?

**Comment by jagi** [comment]
Hmmm I'm open to any ideas that may improve Astronomy. If support for GraphQL is only about possibility to convert Astronomy schema to GraphQL then it may be a good idea. I'm not familiar with GraphQL. I've just heard about it and know main principles.

I'm just curious what are MDG's plans if it goes about React and other related stuff. Are they going to use GraphQL?

**Comment by crussi** [comment]
Hi Jagi,
I can't answer your question directly.  But, I can tell you I've been reading a lot of posts by Kadira (aka meteorhacks) who are doing a lot of work with Meteor + GraphQL.  Their latest post can be found here:
https://voice.kadira.io/meteor-meets-graphql-3cba2e65fd00#.4m7v0oua3

I've watched a few of Facebook's presentations on GraphQL and I was "really" impressed.  But, like you, I still only know the main principles.  That being said, as far as Astronomy is concerned, it would seem more like GraphQL would be useful to coordinate consumption of data from more data sources than just MongoDB.  I realize that is a sketchy response, but, I think it is still a little early to consider using GraphQL with Meteor until things are worked out.

Looking forward to Astronomy v 2.0 ... I'm loving it so far!

**Comment by marbemac** [comment]
I think GraphQL could fit into Astronomy nicely, but would not consider it a priority until the meteor community has had a bit more time to figure out how it fits into the ecosystem.

**Comment by jagi** [comment]
I'm currently doing the course from Kadira about GraphQL and I'm starting to like it a lot. I think I will change API a little bit to make it compatible with GraphQL. However as @marbemac said, support for GraphQL is not a priority, but it's always good to be prepared for it :)

**Comment by talha-asad** [comment]
:+1:

**Comment by zimt28** [comment]
Nice :+1:

**Comment by jagi** [comment]
I've change API of defining fields so that it will be easier in the future to support GraphQL. So we're just waiting what will MDG do in terms of GraphQL :)

**Comment by zimt28** [comment]
Thanks @jagi, I think we can close this for now :)

**Comment by iamrobreynolds** [comment]
With the evolution of Apollo, has any progress been made to use Astronomy with GraphQL? I have my schemas defined with Astronomy and would like to start using GraphQL. Thoughts?

**Comment by lukejagodzinski** [comment]
The more I get familiar with GraphQL the more I'm sure that there is no good fit for Astronomy in GraphQL ecosystem. Astronomy schemas are IMHO much easier to define and read than GraphQL schemas however it would be the only benefit of using Astronomy. In GraphQL there would be no use of Astronomy events or method. The same about save, remove methods. So "Astronomy" would be just a wrapper for schema definition, which I think is pointless.

**Comment by mingz-unity** [comment]
Re-opening this aging post because I needed something like this and looked into implementing it, and here's more detail on what I've got so far: 

First the reason I needed to support GraphQL for Astronomy is for schema definition. There were a couple of things that GraphQL can do well today: 
- Generating an AST tree to walk without type dependencies issues (I have 200+ types and impossible to craft manual code)
- Robust ecosystem for tooling (inspecting / browsing the schema, and generating Typescript interface for strongly typed check) 

I realized the runtime schema definition of Astronomy is very close to GraphQL.js (probably intentional) and that definitely made it easier to support GraphQL Schema on Astronomy. Once the GraphQLSchema tree is generated I was able to walk the AST tree and construct the Astronomy class schema at runtime without dependency issues (and type conversion isn't that hard too). I did run into some problems because there aren't as many features in GraphQL syntax to have 1-1 mapping so I ended up having to use GraphQL directives in a few places (for index, default, etc.) but this seems to be working so far. 

Of course this is not a full support for GraphQL which as Luke said is not very meaningful given the difference of the two system and how data access works. 

If there's interest still in the community for this type of enhancement I can possibly clean out the code and publish it. If there's any suggestions on the approach above I'd also appreciate.

**Comment by lukejagodzinski** [comment]
@mingz-unity recently I'm using two tools to deal with this problem.
For ORM I use this https://github.com/typeorm/typeorm which is one of the best tools I've used. Its syntax is also based on other tools like Doctrine, which was also inspiration for Astronomy. And it supports more databases. It can work with both pure JS and TypeScript.

For GraphQL management I use https://github.com/19majkel94/type-graphql which is a tool designed to work well with typeorm. Using those two tools made my life easier. The only downside is that if you don't want to use TypeScript, then it will not be as handy. So I only recommend that if you're into TS.

I will probably create some video tutorials on how to use them together
