### ISSUE TITLE
getModified() does not get the data model is initialized with. Should it?

### ISSUE THREAD

**Issue by awei01** [jagi/meteor-astronomy#255]
Currently the `.getModified()` only works on models that actually have been saved. Should it also work on newly instantiated models?

```
var Foo = Astro.createClass({
    name: "Foo",
    fields: { value: "string" }
});

var foo = new Foo({ value: "original" });
foo.set('value', 'something new');
console.log(foo.getModified(true));  // { value: null }, but one might expect { value: "original" }

```

**Comment by jagi** [comment]
You know assumption was that entire object is like "modified" when it's new. But in deed it could display what has changed from the initial state. I will definitely implement it in 2.0 however I don't want to mess with 1.0 right now because it's stopping me from releasing 2.0. If it's not a big deal please forgive me and wait for 2.0 :)

**Comment by awei01** [comment]
Ok, np
