### ISSUE TITLE
Release a 2.0 Beta

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#258]
Hi @jagi,

I know you've been very busy implementing all the features for Astronomy 2.0. I would suggest you release a beta build for 2.0 which I and other users will be able to help you test out. I think this approach will make it easier for you and other astronomy users to transition to the new version when you release the first stable build. We can also create an issue which explains migration from 1.0 to 2.0 beta and can later add that to the documentation once a stable build is released.

Let me know your thoughts. I would very much like to switch to 2.0 even if it seems to be missing a few features.

**Comment by zimt28** [comment]
You can always pull the `v2` branch from here into you `/packages` folder and try it already!

**Comment by jagi** [comment]
As @zimt28 said you can always clone the `v2` branch. However, the API is changing a lot right now and I want to avoid developers frustration and GitHub issues. For example, yesterday I've changed the way how fields are defined which caused all tests to fail. So, if you want to try it out you can be you're doing it on your own risk :). I will notify when it's ready to test. After publishing info about 2.0 I've received several requests for features and that's why API is changing because even if I'm not implementing them right now I want to support them in the future and have to be prepared for that.

**Comment by jagi** [comment]
Actually the plan has changed. I will release not full featured version (RC.1) until the end of this week or at the beginning of the next one.

**Comment by talha-asad** [comment]
@jagi Thanks. I will give it a try later this week.
