### ISSUE TITLE
emitting custom events?

### ISSUE THREAD

**Issue by dovrosenberg** [jagi/meteor-astronomy#26]
Is it possible for behaviors to emit custom events?  For example, I'm doing a slightly different variant on softdelete that actually just runs on a remove via beforeremove.  It flags the object as deleted and cancels the remove.  Because the remove was cancelled, the afterremove event no longer fires (I assume).  And it shouldn't.  

But I'd like the ability to emit an "aftersoftdelete" event that objects with this behavior could handle.

Is that possible?

**Comment by jagi** [comment]
Yes it's possible. The `beforesoftremove` and `aftersoftremove` events are triggered in the `softremove` behavior. Take a look at this line https://github.com/jagi/meteor-astronomy-softremove-behavior/blob/master/lib/behavior/methods.js#L23. There is a little "error", because I'm calling camel case `beforeSoftRemove` event and in fact I should call `beforesoftremove`. However as far as events names are case insensitive you can use both ways. However according to the standard in JS you should use the lowercase form.

**Comment by dovrosenberg** [comment]
Got it.  Thanks.
