### ISSUE TITLE
EJSON custom types vs Astronomy custom types

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#260]
I don't know if this has been discussed before. I was trying to understand why schema definition uses ```{type: 'string'}``` or ```'string'``` rather than ```String```.

I know this way makes it really easy to define custom astronomy types and use them in your schema, but if you start supporting EJSON custom types and base types, i think it will make it a bit more easy for anyone who understands EJSON to define custom types. 

Pros:

1) Less documentation required, just point to EJSON docs on meteor.
2) Better serialization?
3) Less code for custom types in astronomy.

Cons:
1) Migration will need a bit more work.

I would like your thoughts on this.

**Comment by jagi** [comment]
Yesterday I've switched API to `String` from the `"string"`. That's because of support for GraphQL. I don't agree with any of the pros you've mentioned. In fact it does not matter what definition type you will use. It does not even matter if it goes about GraphQL. The thing that is important is how nested fields are defined. Right now you will define list of tags `[String]` or list of phone number `[Phones]` or address `Address`.

However, yes I'm switching to this type of fields definition and I think it will be a little bit easier for some people.

**Comment by talha-asad** [comment]
I am happy that you switched to unquoted syntax, but i don't exactly see the problem with nested fields. Could you give an example.

**Comment by jagi** [comment]
Before this change I was using the following syntax for nested fields definition:

```js
nested: {
  tags: {
    count: 'many',
    type: 'String',
    /* ... */
  },
  address: {
    count: 'one',
    class: 'Address',
    /* ... */
  },
  phones: {
    count: 'many',
    class: 'Phone',
    /* ... */
  }
},
fields: {
  /* regular fields here */
}
```

So as you can see, syntax is quite complex. Right now it's just:

```js
fields: {
  tags: [String],
  address: Address',
  phones: [Phone]
  /* regular and nested fields together */
}
```

and if you take at how GraphQL types are defined it's in similar fashion

**Comment by talha-asad** [comment]
I like the approach you have taken. Makes more sense and is less verbose.
