### ISSUE TITLE
afterSet event fires on remove() and Collection.find()

### ISSUE THREAD

**Issue by negamaxi** [jagi/meteor-astronomy#261]
Perhaps I misunderstood appropriate behavior of before/afterSet events, but it seems like it fires on every action I perform e.g. inc(), pull(), save(), even when simply fetch document from db with find/findOne. Moreover it fires for every field in a document.

Code looks like that:
``` javascript
Movie = Astro.Class({
	name: 'Movie',
	collection: Movies,
	fields: {
            //fields
	},
	events: {
		'afterSet': function(e) {
			console.log(e); // this fires on every action for every field
			var field = e.data.fieldName,
			      value = e.data.setValue;
			if (field == 'titles') {
				//do stuff for set('titles')
			} else if (field == 'date') {
				//do stuff for set('date')
			}
		},
		'beforeRemove': function() {
		},
	}
});

```
And here is example of method with no set() action performed, but it fires afterSet anyway.
``` javascript
Meteor.methods({
	'removeMovie': function(id)
	{
		if (Meteor.user().editor)
		{
			var doc = Movies.findOne({'_id': id});
			doc.remove();
		}
	}
});
```
By the way, I've split afterSet event with blocks of code for every field i need, and it looks awful :) Is there any way to create modification events on field level, rather then class/global? Thanks!

**Comment by jagi** [comment]
Yes the `set` events are executed because Astronomy is very often setting some fields values. Even when you remove a document it's setting the `_id` property to `null` so that's why the `set` event is called. I'm not going to change it right now. You have to check `event` argument of the event handler to determine what field was changed, that's the only way of doing it on the "field level".

In Astronomy 2.0 there is not `set` event. There is the `change` event which is executed only on document save. So you may wait for the next version. That should solve your problem.

**Comment by negamaxi** [comment]
From 2.0 feature-list seems like it'll solve a lot of my problems) Good luck with next version.
