### ISSUE TITLE
_getModifier() triggers one beforeset event per field making isModified() spam beforeset events

### ISSUE THREAD

**Issue by elidoran** [jagi/meteor-astronomy#264]
[isModifed()](https://github.com/jagi/meteor-astronomy/blob/master/lib/modules/fields/modified.js#L45) uses `_getModifers()`.

[_getModifers()](https://github.com/jagi/meteor-astronomy/blob/master/lib/modules/fields/modifiers.js#L294) loops on [all modifers](https://github.com/jagi/meteor-astronomy/blob/master/lib/modules/fields/modifiers.js#L3) and calls `_getModifier()`.

[_getModifier()](https://github.com/jagi/meteor-astronomy/blob/master/lib/modules/fields/modifiers.js#L235) does `var originalDoc = Class.findOne(doc._id);`.

That gets another instance of the document and triggers a *before set* event for each field in the document found.

There are [5 modifiers](https://github.com/jagi/meteor-astronomy/blob/master/lib/modules/fields/modifiers.js#L3) in the list. So, for a document with 10 fields, the *before set* event will run 50 times when a call to `isModified()` is made.

Is that behavior intentional, or, is it possible I've used something wrong causing it to do that?

I want to do some work on a field when it is being set, so, I'm using a *before set* event. However, that logic is running a gazillion times when I call `isModified()`. 

Could the *before set* event run with an object containing all the key/value pairs being set instead of running one event per key/value pair? That would at least lessen it down to running 5 times (once per modifier). Then perhaps an optimization could be `_getModifers()` does the findOne() op and provides it to `_getModifer()` so it doesn't repeat it? If `_getModifer()` is called from elsewhere and the originalDoc isn't provided then it could grab it on its own. 

I'm sure this has probably changed in v2.0, but, I thought I'd check with you. :)

**Comment by elidoran** [comment]
This package is well written. It was very easy to fork this and tryout some changes. 

I basically swapped around _setOne and _setMany so _setOne calls _setMany and all the work is done there. Then, changed a couple places which iterated over key/value pairs and called _setOne each time to instead call _setMany. 

Voila. Now it does one event.

Thank you for writing this, and for writing it so well.

**Comment by elidoran** [comment]
Oh, I also passed the originalDoc from _getModifiers() to _getModifier() and had _getModifier() only get originalDoc when it wasn't specified.

With both changes it reduced the many events to one.

**Comment by jagi** [comment]
The problem with the `set` events is that I had to use them also on document initialization which is also done on `doc._getOriginal()`. I had to make this because there are behaviors that are using `beforeSet` or `afterSet` events to execute some logic on document initialization. That was probably a mistake. I'm not going to fix this in 1.0 because it would be compatibility breaking feature.

In deed, in 2.0 I've fixed it and there are not `set` events at all :P. Right now, we only have the `change` event that will get called on document save. I will explain everything in a documentation for 2.0. Developers will not lose any functionalities because of that. There will be just a few changes in how they need to approach given problems.
