### ISSUE TITLE
Mention the prior art: SimpleSchema, CollectionHooks, Collection Behaviors

### ISSUE THREAD

**Issue by dandv** [jagi/meteor-astronomy#27]
Many people in the Meteor community are familiar with @aldeed's [SimpleSchema](https://github.com/aldeed/meteor-simple-schema) and @matb33's [CollectionHooks](https://atmospherejs.com/matb33/collection-hooks). @Sewdn's [collection-behaviors](https://github.com/Sewdn/meteor-collection-behaviours) is another [prior art](https://en.wikipedia.org/wiki/Prior_art) that also seems to have been used as source of inspiration.

After reading the documentation, Astronomy seems to reinvent all these three packages and [use neither](https://github.com/jagi/meteor-astronomy/blob/master/package.js). A lot of work has gone into both SimpleSchema, CollectionHooks and Collection Behaviors on one hand, and Astronomy on the other. There are probably good reasons for not reusing the  existing packages, and why Astronomy decided to build its own schema, hooks and behaviors. Users would love to know these.

Thanks!

**Comment by jagi** [comment]
First of all, the first version of the package was created summer 2013 and it was about the same time the aldeed's package was created. That time no one known about simple schema. My package was not inspired by simple schema.

If I'm reinventing the wheel I would like to ask why I receive many comments that my package is far more better than simple schema? If you want I can post many of them here. But after using astronomy and simple schema, people can just choose their favourite tool.

Moreover the concept of MVC, behaviors, hooks is not new and wan't invented by aldeed. My package was inspired by PHP Doctrine library and when you look at my code you will see many similarities and you won't see these similarities between astronomy and simple schema.

**Comment by dandv** [comment]
Thanks, this is informative. I didn't know when Astronomy was created. Might be worth adding this little bit of history to the README.

> After using astronomy and simple schema, people can just choose their favourite tool.

I'm a new user, and haven't used Astronomy. The majority of users will be in this category, and some of them will have used SimpleSchema. These users will want to know how Astronomy (which will hopefully become popular) is better or easier than Simple Schema (which is very popular).

A comparison will help.

For example, [Flow Router explains how it's different from the much more popular Iron Router](https://github.com/meteorhacks/flow-router#difference-with-iron-router).

**Comment by jagi** [comment]
The first public version was named `verin-model` and you can find it here https://github.com/jagi/verin-model. The first commit was made Oct 26, 2013 however it was already working library, so I've started creating it few month before. It can be dated on mid 2013 :). Originally it was named `zeitgeist-model` because it was a model layer for Zeitgeist website and I decided to share it with a community. At the beginning it was simple package but with the time the original idea had been improved to be what it is now :).

But yes, I think writing a little bit about history of the package can be good idea. I will definitely do it :). Thanks for this suggestion.

> The majority of users will be in this category, and some of them will have used SimpleSchema, These users will want to know how Astronomy /* ... */ is better or easier than Simple Schema 

Yes probably you are right, but you know I don't like to say things like: "Hey guys, here is my package it's much better than SimpleSchema. Just leave your old tool because mine is better" :). I'm glad that people like it and I received many comments that it's actually better than SimpleSchema. Many people coming from other languages (especially PHP) are glad that they can use similar approach when creating model. Maybe I will try pointing differences without saying that my work is better.

> which will hopefully become popular with a bit of marketing

Yes I need to make it more popular. People just need to know that it exists. I have an idea how to achieve that. I'm creating video tutorial about Astronomy. When I'm finished I will publish it on Twitter (with proper tags) and send it to the Meteor team. I hope that they will post info about it on their FB and Twitter profiles. But I don't want to promote to widely unfinished product. But I'm almost ready. The 1.0.0 version is closer and closer.

I will take your suggestions into account :). Thanks!

**Comment by aldeed** [comment]
I like competition.

**Comment by frankapimenta** [comment]
jagi :+1:

**Comment by jagi** [comment]
Ok I've added two sections **History** and **Why use Astronomy?**
I hope that I did not exaggerated :)
I'm closing this issue for now

**Comment by dandv** [comment]
:+1: !

BTW, out of curiosity, how/where were the testimonials received? I hope [Atmosphere implements comments soon](https://github.com/percolatestudio/atmosphere/issues/182) because that's exactly where these testimonials should go..

**Comment by jagi** [comment]
Great idea with the comments on the Atmosphere!
Right now comments mostly comes from GitHub issues and from Crater.io https://crater.io/posts/MT9dPLYiydEWmqYi5/comment/tCQH3LGahRQDhCkNs

**Comment by aldeed** [comment]
Here's another one for you:

"If this package were around when I created SimpleSchema, I would have used it instead of creating SimpleSchema."

It looks pretty slick. People only like SimpleSchema because it was the first decent schema package with good test coverage for Meteor. (And because they want to use AutoForm.) They'll eventually move on.

Speaking of AutoForm, the AF schema logic could be abstracted pretty easily allowing this or other types of schemas to be used instead of SimpleSchema/Collection2. It's on the "someday" list.

**Comment by dandv** [comment]
+ :100: for @aldeed for that testimonial.

**Comment by jagi** [comment]
@aldeed I appreciate it :)

@rclai said that he will work on the package allowing transformation of SimpleSchema to Astronomy schema and vice versa.

This Friday I'm going on two weeks vacation but after that I will focus on Astronomy Forms package.

**Comment by dandv** [comment]
Thanks for all your work!

BTW another "prior art" package I hadn't mentioned: @dburles [collection-helpers](https://atmospherejs.com/dburles/collection-helpers)

**Comment by rclai** [comment]
I haven't gotten the chance to work on that transformation package yet. I was going to wait until Astronomy was more ready before I do that. Thanks again for [making it easier to see the validation definitions](https://github.com/jagi/meteor-astronomy-validators/issues/4).

**Comment by jagi** [comment]
@rclai sounds good. 1.0.0 is very close.

**Comment by dandv** [comment]
Very similar project: @emmerge:[graviton](https://atmospherejs.com/emmerge/graviton) by @mhwheeler and @fractallian.

**Comment by jagi** [comment]
Ok thanks I will add it to the list
