### ISSUE TITLE
Soft Remove and duplicates don't cooperate

### ISSUE THREAD

**Issue by mp27** [jagi/meteor-astronomy#315]
Story: I have an AstroClass  and I want  a certain field to be unique.
However , after I soft remove the document, the unique validator still finds that field. And unique throws an error. Because it's not unique. Even though after soft removal, it should be. 
Is it supposed to work this way? It is a bug , an intentional feature, it's by design, or is it my mistake ?Thank you.

**Comment by jagi** [comment]
Hmm unfortunately it's seems to be a bug and one that would be hard to fix. Because there may be other situations with similar effect. What I would recommend is checking uniqueness by hand.

**Comment by s7dhansh** [comment]
@mp27 since the soft-removed doc is still there in the db, and the uniqueness is checked on the db (and not in the astronomy middle layer), I don't think this will ever be possible. Checking uniquness in Astronomy, will always be a bad idea, as it is a database's job.
I will suggest that before softremoving such docs, just prefix/suffix the unique field with say "del-". It will retail your uniqueness. You can simply write wrapper methods for softremove/restore:

```
methods: {
  markRemoved() {
    this.xyz = this.xyz + "-del";
    this.save();
  },
  restoreFromTrash() {
   this.zyz = this.xyz.replace("del-", "");
   this.save();
  }
}
```

You may have to make this more accurate by adding a counter with del, to ensure uniquness. I suggest you do that on the server by finding the existence of such documents and the counter required.
