### ISSUE TITLE
Strange conflict with ViewModel and Astronomy

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#317]
I'm using **Astronomy** (with sort, softremove and timestamp) and **manuel:viewmodel** in a project together. I like both, but I've had a few hiccups trying to use them together.

I came upon a weird problem, where my reactively created ViewModel's _click-bindings_ wouldn't register when adding new documents to a collection, until I refreshed the page.

A repro of the issue can be found here: [viewmodel-click-bind](https://github.com/arggh/viewmodel-click-bind
)
If you just add a few lists and try to select between them, you will see what I mean. 

According to ViewModel's creator, this is caused by how Astronomy manipulates the collection/documents. A simple quickfix is to `.fetch()` the documents before iterating, which might help to pinpoint the actual cause.

I would love to understand what is wrong here and how to fix it.

Ideas?

**Comment by arggh** [comment]
The [issue in ViewModel repo](https://github.com/ManuelDeLeon/viewmodel/issues/214) was now resolved by a change in ViewModel - however, the conclusion seemed to be that Astronomy messes up Blaze's onViewReady-callback somehow. Not sure if looking into this from Astronomy's side is beneficial or not.

**Comment by jagi** [comment]
Astronomy does not mess with Blaze at all, so that's not a point. I don't have time to check if every package works correctly with Astronomy. Most of the problems should be solved with Astronomy 2.0 as it does not change anything about collections. The most common problem was transforming plain documents fetched from the collection into Astronomy objects which didn't play nice with some packages.  In most cases you can just set `transform` to `null` and it should work.
