### ISSUE TITLE
v2.0 Field values set onBeforeInsert/Update events are not updated in the document

### ISSUE THREAD

**Issue by ochicf** [jagi/meteor-astronomy#343]
Hi,

I'm working on a similar behavior as the timestamp and while playing with it I've noticed that the fields do not get any value at all after the document insertion.

``` js
// /lib/collections/post.js
import {Mongo} from 'meteor/mongo';

const Posts = new Mongo.Collection('posts');

const Post = Astro.Class.create({
  name: 'Post',
  collection: Posts,
  behaviors: {
    timestamp: {},
  },
});
export {Post};
```

``` js
// somewhere on /client/*
import {Post} from '/lib/collections/post.js';

let post = new Post();
post.save();
console.log(post.createdAt); // undefined

post = Post.findOne({_id: post._id});
console.log(post.createdAt); // Wed Apr 13 2016 12:45:48 GMT+0200 (CEST)
```

According to the 1.2.10 documentation the document should be updated after it has called the `save` operation, so I'm guessing this problem is from 2.0 only.

**Comment by lukejagodzinski** [comment]
Hmmm in deed it's not setting the `createdAt` field on the client. You can still do:

``` js
doc.save();
doc.reload();
doc.createdAt; // correct date
```

However, it should set date on the client too. I will take a look at it.

**Comment by lukejagodzinski** [comment]
Hmmm the problem is more complicated. In v2, I'm using meteor methods to store document in a collection. And I forgot that meteor methods just copy object being passed, so reference is lost. There are two ways to overcome this, not calling method on the client or reloading document automatically after save. I don't know what solution to use because both of them has pros and cons... I have to rethink this.

**Comment by lukejagodzinski** [comment]
Ok I've investigated a problem and I'm not gonna change the way it works right now. It's expected behavior. When you do `Collection.insert()` the method that gets called behind the scene is also losing all the data that was produced by the method. The same happens when you call `doc.save()`. The Meteor method that gets called behind the scene loses on the client all the data that it produced. So, it's developer's decision if he/she wants to get that data. In most cases you don't want to. But if you really want to get data that was produced by the method you have to do:

``` js
// On the client it's asynchronous
var doc = new Doc();
doc.save(function() {
  doc.reload();
});
```

``` js
// On the server you can use synchronous calls
var doc = new Doc();
doc.save();
doc.reload();
```

I will add such information in the documentation
