### ISSUE TITLE
Client side validation fails when a specific field is added to the class

### ISSUE THREAD

**Issue by Ben305** [jagi/meteor-astronomy#344]
I am currently migrating from Astronomy 1.2.10 to 2.0.0-rc.8 and ran into the following problem:

The client side validation for fieldA (type _String_, validator _choice_) failed. I was able to track down the cause: As soon as I include the field _length_ (type _Number_, with default value) in the same class, the validation for fieldA fails.

I have a sample application ready that can be used to reproduce the problem:
https://github.com/Ben305/AstroV2ValidationSample

Just execute _runTests.sh_ in the SampleApp directory. The tests will succeed, until the field _length_ is added to the sample class (you just need to uncomment the definition).

**Comment by lukejagodzinski** [comment]
I assume that it may be caused by the field name `length`. Have you tried with different field name?

**Comment by Ben305** [comment]
Yes, that seems to be the cause. Do you have an idea what's wrong with it? It was perfectly working in Astro 1.2.x.

**Comment by lukejagodzinski** [comment]
I will take a look at it. I know there was already a problem with the `length` name but I think that I solved it. I will take a lot at it. It shouldn't be a big problem. The cause of the problem is how underscore or lodash treats the `length` property on the object level. One of them treats it as the property, the other one as the array length.

**Comment by lukejagodzinski** [comment]
I run tests and it fails in both situations with and without the `length` field. In fact validation does not work with Mocha tests at all. So the problem is not in Astronomy but how Mocha plays with Astronomy. I don't have time to check it right now. You have to investigate it by yourself if you want to use Mocha tests.
