### ISSUE TITLE
beforeFind event on a base model (rc.5)

### ISSUE THREAD

**Issue by Andrew1431** [jagi/meteor-astronomy#362]
Hey there! Docs are looking freaking sexy!!!

Uhm we're using rc.5 on our application right now as upgrading is currently causing a few breakages, but we have a Base model that all of our models in our application extend off of. That base model has a beforeFind event that is not getting fired when finding on any of the inherited classes. beforeUpdate, beforeInsert both properly fire but not beforeFind. Any way to work around this / and|or was the a bug in version rc.5 that has been since fixed? thanks.

**Comment by Andrew1431** [comment]
It could be that the base model doesn't have a collection, and as such the beforeFind isn't being registered, but you would think that event would still get sent through inherited models.

**Comment by lukejagodzinski** [comment]
@Andrew1431 hmmm I will take a look at it

**Comment by lukejagodzinski** [comment]
Ok I've investigated it. Sorry that it took me so much time but I'm on business trip and don't have a lot of time to deal with Astronomy. However if it goes about your problem there are several things worth mentioning. First of all, there is no point of adding the `beforeFind` event to classes that does not have collection. The second thing is that the `beforeFind` event will be inherited anyway but never invoked because it don't have associated collection. You can check what registered events have a class by calling `YourClassName.getEvents()`. If you're trying to use some complicated structure of inheritance, then be informed that I'm going to improve some features, like there will be a way of storing child classes in different collections or just changing typeField for a child class etc.
