### ISSUE TITLE
Are there uppercase and trim setters / transforms?

### ISSUE THREAD

**Issue by ragulka** [jagi/meteor-astronomy#382]
Is there anything in Astronomy that's equivalent to Mongoose's trim() and uppercase() setters like described here: http://mongoosejs.com/docs/api.html#schema_string_SchemaString-uppercase

So that we could do something like:

``` javascript
country: {
  type: String
  uppercase: true; 
}
```

or perhaps there is already a way to do it, but I can't see it in the docs?

**Comment by lukejagodzinski** [comment]
You could eventually add such a module to Astronomy that would allow that. Right now the only way of doing it is using the `beforeSave` hooks/events.

``` js
beforeSave(e) {
  const doc = e.currentTarget;
  doc.country = doc.country.toUpperCase();
}
```

However, as I said you can create a module that would look for the `uppercase` property in the field definition and just do it automatically. I haven't described how to create custom module yet. So the only way to learn right now is to check how Astronomy modules are implemented. It's not very hard, so you can try that. I'm not going to introduce such feature in Astronomy itself because is rare use case.
