### ISSUE TITLE
Is .save() synchronous or asynchronous? And where? (client/server)

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#404]
I noticed in Astro v2, you can have a callback function for `.save()`. But as far as I can see, the documentation doesn't explain whether a callback is necessary, and when. Is `.save()` synchronous on the server, but not on the client (callback required)? What if I need an ID to proceed with an operation, e.g.:

(code is shared between client & server)

``` javascript
  run({ attachment, id, type }) {
    const a = new Attachment({ ...attachment, userId: this.userId });
    const attachmentId = a.save();
    let model, item;

    switch (type) {
      case 'INSIGHT':
        model = Insight;
        break;
      default:
        throw new Meteor.Error('type-error', 'Unsupported item type');
    }

    item = model.findOne(id);

    if (item) {
      item.attachments.push(attachmentId);
      item.save();
    } else {
      throw new Meteor.Error('no-such-object', `${type} ID ${id} not found`);
    }
  },
```

Is this correct, or do I need to be using a callback?

**Comment by lukejagodzinski** [comment]
On the server the save operation is synchronous however you can still pass callback function. The `save` and `remove` methods work in the same way as `Collection.insert/update/upsert/remove`. So you can just read Meteor documentation:

> On the server, if you don’t provide a callback, then insert blocks until the database acknowledges the write, or throws an exception if something went wrong. If you do provide a callback, insert still returns the ID immediately. Once the insert completes (or fails), the callback is called with error and result arguments. In an error case, result is undefined. If the insert is successful, error is undefined and result is the new document ID.
> 
> On the client, insert never blocks. If you do not provide a callback and the insert fails on the server, then Meteor will log a warning to the console. If you provide a callback, Meteor will call that function with error and result arguments. In an error case, result is undefined. If the insert is successful, error is undefined and result is the new document ID.

The only difference is that, when you don't provide callback function on the client it will throw validation errors instead logging to the console if no callback function provided. There is a bug that was already fixed in the version that is on GitHub, that it does not return ID immediately on the client when inserting  a document.

**Comment by ffxsam** [comment]
Excellent - thanks for the clarification!

**Comment by laurentpayot** [comment]
It would be worth mentioning in the docs.
