### ISSUE TITLE
Camel case lifecycle function names

### ISSUE THREAD

**Issue by dcworldwide** [jagi/meteor-astronomy#43]
Hi,

This may just be a documentation issue, but some of the lifecycle event functions in https://github.com/jagi/meteor-astronomy/wiki/Behaviors are not camel case. I think we should be consistent everywhere.

e.g. 

addbehavior
initclass
initinstance

**Comment by jagi** [comment]
Hi,

There already was a talk about this and as I explained both forms are acceptable. The one that is specified by W3C is lowercase however throughout the Internet the came lcase seems to be used more often because it's more readable. If so many users want it came case, so maybe it's the one we should use in the documentation.

**Comment by dcworldwide** [comment]
Thats good news. Thanks.
