### ISSUE TITLE
A few question aboit validators. 

### ISSUE THREAD

**Issue by Tbutnyakov** [jagi/meteor-astronomy#451]
Hey, Jagi!
I have a two questions about validatiors. 
**1. Required validator**
I have a problem with 'required' validator. 
For example, i can put absolutely clear, like "" value, and validator will not generate "err" message. 
Astronomy will save it. 

> content: {
>             type: String,
>             validators: [{
>                 type: 'required',
>                 message: 'Not now! I am won't work!'
>             }]
>   }

What i doing wrong?

**2. Unique option**
I remember, Astronomy 1 had "unique" option which does not allow to store duplicates. What we need use in Astronomy 2 for this case?

**Comment by lukejagodzinski** [comment]
Hi
1. Empty string is non-null/non-undefined value so that's why it doesn't throw any error. All fields in Astronomy 2.0 are required by default so you don't need to use it here. Instead you can use the `minLength` validator with a param `1`
2. In 2.0 there is no `unique` validator. You should use `unique` index instead which will throw error on insert operation.

**Comment by Tbutnyakov** [comment]
Hello, Jagi!
Thanks for reply, yeasterday i did the same, but i just needed to check. 
Thank you for awesome package!
