### ISSUE TITLE
afterChange event no longer available in V2

### ISSUE THREAD

**Issue by robertpitt** [jagi/meteor-astronomy#459]
Hey,

Im currently working on upgrading the version of Astronomer to V2 for one of our project but have come across an issue with the events.

In our application we require the ability to monitor individual property changes and we was doing this via the `beforeChange` and `afterChange` events but now they do not fire.

In V2 I cannot see any reference to events that are fired on individual property mutations.

Any advice would be appreciated.

Thanks

**Comment by lukejagodzinski** [comment]
It was removed because of performance reason. Firing `change` events on every document mutation was overkill. Right now you have to handle that in the `beforeUpdate` and `afterUpdate` events. You can get modified fields `const modified = e.target.getModified()` or check if a given field was modified `e.target.isModified('fieldName')`. However if you want to monitor several fields  the first approach will be faster.
