### ISSUE TITLE
_isNew is always true during afterInit event

### ISSUE THREAD

**Issue by talha-asad** [jagi/meteor-astronomy#482]
Always true during the `afterInit` event, regardless if you use `findOne` or create a new one using `new`.

I know this is an internal property but due to lack of another way to know if the doc is a new one or an already existing one, I have been using this property.

**Comment by lukejagodzinski** [comment]
Hmm it's seems to big a bug but changing that right now can cause some unexpected problems in some behaviors or apps that are already using Astronomy. So I'm not convinced to change it right now.

**Comment by talha-asad** [comment]
Resolving this issue, do you think it will become easier to fix #478 as well?

I would like to contribute, can you give me some pointers or share an approach?

**Comment by lukejagodzinski** [comment]
To resolve this issue you probably have to look for the solution in the `transformToClass` util https://github.com/jagi/meteor-astronomy/blob/4ae9e7178c567362cf9b5fce898e93048e4b72b4/lib/modules/storage/utils/transform_to_class.js#L31

As you can see it sets `_isNew` to `false` but after `before/afterInit` events have already been triggered. One of the solutions could be passing `_isNew` flag as an option to the document constructor and set it there just before triggering events. We can't also assume that a document with ID is a NOT new document as someone may want to insert a document with his/her custom ID. So the problem seems to be related only with the `findOne/find` methods, where we are use that document is already stored in a collection.

If it goes about the `raw` method it's pretty simple to do but I will do it by myself as I have some free time. As always I have some extra work to do for family and friends.

**Comment by lukejagodzinski** [comment]
Bug fix prepared but not published yet. Sorry that it took me so long to implement it but 1. I forgot about it entirely 2. It wasn't so easy to fix. With this fix, there will be a little change in API, but backward compatibility will be preserved. From new version usage of the `doc._isNew` will be deprecated. Right now you should use `Class.isNew(doc)`. However you can still use `doc._isNew` and it will work as described in this issue.

I will release this fix soon.
