### ISSUE TITLE
Adding transformed documents to a local collection fails

### ISSUE THREAD

**Issue by arggh** [jagi/meteor-astronomy#497]
With Astronomy V1 I could insert my documents to a local collection on the client like this:

```
LocalDocuments = new Mongo.Collection(null);

addToLocal(id) {
  let doc = Document.findOne(id); // Document being defined as Astronomy Class
  LocalDocuments.insert(doc);
}
```

with V2, I get this:

```
collection.js:535 Uncaught TypeError: Class.getName is not a functiontoJSONValue @ class.js:117(anonymous function) @ ejson.js:168Meteor._noYieldsAllowed @ fiber_stubs_client.js:7toJSONValue @ ejson.js:167toJSONValueHelper @ ejson.js:237EJSON.toJSONValue @ ejson.js:249EJSON.clone @ ejson.js:496LocalCollection.insert @ minimongo.js:545insert @ collection.js:528setSelected @ checkbox_cell.js:16toggleSelected @ checkbox_cell.js:9setValue @ manuel_viewmodel.js?hash=62f2f73…:955(anonymous function) @ manuel_viewmodel.js?hash=62f2f73…:974(anonymous function) @ viewmodel-parseBind.coffee:17dispatch @ jquery.js:5110elemData.handle @ jquery.js:4918
```

Is this a known limitation? I think being able to store documents on a temporary collection is huge benefit of Minimongo and would be nice, if Astronomy documents would play along.

**Comment by lukejagodzinski** [comment]
It's not a bug in Astronomy but rather bug/feature in Meteor. When you try to save document into local collection it tries to serialise astronomy document but it's not an original document. It's a copy of it but bad copy. It does not contain information about class it is instance of, that's why the error `Class.getName is not a function` because it's looking for the `getName` method in the `Object` constructor. So it's definitely bug/feature in Meteor. What you should do to avoid this error is sth like this:

``` js
addToLocal(id) {
  let doc = Document.findOne(id); // Document being defined as Astronomy Class
  LocalDocuments.insert(doc.raw());
}
```

**Comment by arggh** [comment]
That's how I solved it already for my use case, I just lose the Astronomy-goodness like Class methods, but that's not a big deal since I can always summon up the "original document" when needed.

I just wanted to post this since it used to work in V1 and my app relied on it, and now it's "broken" with V2.

I'll close the ticket since from what I understood, there's no fix planned.

**Comment by lukejagodzinski** [comment]
It's actually not broken. You can't store in local collection documents being instances of classes. Collections can only store plain JS objects. I don't know precisely why it worked in v1 but it was probably related with different way of EJSON-ification. However if you want to store astronomy document in reactive containers you can use ReactiveVar, ReactiveDict, [ReactiveMap](https://atmospherejs.com/jagi/reactive-map) or [ReactiveArray](https://atmospherejs.com/jagi/reactive-array) or other reactive containers.

However I will investigate this problem and check if I can bring back the old behavior.

**Comment by lukejagodzinski** [comment]
If you want to retain "Astronomy class goodness" then you can do something like:

``` js
LocalDocuments = new Mongo.Collection(null, {
  transform(doc) {
    return new Document(doc);
  }
);
```

But you still have to store plain objects there (`doc.raw()`).

**Comment by arggh** [comment]
Thanks for the detailed explanation. I didn't know I can attach a transform function to the collection, that's a perfect solution for me.

**Comment by lukejagodzinski** [comment]
I've investigated this problem and the problems seems to be in how inheritance is constructed in Babel plugin. The problem in Collection.insert is in the line `_.extend({}, doc)` which makes a copy of a document which removes information about the class that constructed a document. In v1 where I've implemented prototypal inheritance by hand even when I lost information about the class, all the methods of the class were still copied. However in Babel inheritance is probably implemented in different way and all the class methods are just omitted.

**Comment by bhishp** [comment]
I had an un-related error of  `Class.getName is not a function` when calling a Meteor Method on a model from the client, so for anyone else who might come across the same error.

It was because of the context of `this` that I was passing to the underlying `wrapMethod` performed by astronomy when calling the meteor method was actually the window - rather than the doc. This was because I was passing my meteor method directly to my react component like such:

`<Component handleSubmit={myDoc.meteorMethodForSubmit} />`

I fixed it by:

`<Component handleSubmit={data => myDoc.meteorMethodForSubmit(data)} />`
