### ISSUE TITLE
Server side transform breaks Automatic documents transformation

### ISSUE THREAD

**Issue by banglashi** [jagi/meteor-astronomy#5]
Hi @jagi,

Perhaps you can help me out here. As soon as I do a server-side transformation the astronomy "Automatic document transformation" doesn't work anymore. Perhaps you have some insights you can give me on this on how to make it work?

I created a repo showing the issue here https://github.com/banglashi/astronomy-serverside-transform

Let me know if you need any more information. Thanks.

**Comment by jagi** [comment]
Right now I would discourage you from modifying Astronomy objects on publication. Astronomy objects can't be sent over DDP right now, and I will be working on it soon. It's on my TODO list. Astronomy objects have to EJSONable to allow that. However if you really want to do this there is a way. Here are changes you have to make to your code:

First change is the transform function. I've commented CHANGES.
```js
var transform = function(doc) {
  // YOU HAVE TO GET SIMPLE OBJECT FROM ASTRONOMY OBJECT USING GET() FUNCTION
  var obj = doc.get();

  var lastMessage = Messages.findOne({
    chatId: obj._id
  }, {
    sort: {
      createdAt: -1
    },
    // YOU HAVE TO TURN OF AUTOMATIC DOCUMENTS TRANSFORMATION
    transform: null
  });

  obj.lastMessage = lastMessage;

  return obj;
};
```

You have also modify your `Chat` class schema to have `lastMessage` field.

```js
Chat = Astronomy.Class({
  name: 'Chat',
  collection: Chats,
  fields: {
    title: {
      type: 'string'
    },
    // THE lastMessage FIELD HAS TO BE DEFINED IN THE SCHEMA
    lastMessage: {
      type: 'object'
    }
  }
});
```

Thanks to that, you will receive all the objects as you want. However when you call:

```js
var chat = Chats.findOne();
console.log(chat); // Astronomy object.
console.log(chat.lastMessage); // Not Astronomy object!
```

You won't get Astronomy object calling `chat.lastMessage` it's because there are not relations defined. It's also on my TODO list because it's closely related to EJSONinification of Astronomy documents.

**Comment by banglashi** [comment]
Thanks a lot for the quick reply and the explanation, appreciate it. Keep up the good work and let me know if I can help with anything.

**Comment by jagi** [comment]
No problem :). I'm glad that you and others are testing this package. Thanks to that I can move it forward to the point where it will be fully usable and fit almost all needs. If you want to help, please watch [this](https://github.com/jagi/meteor-astronomy/subscription) and other Astronomy [repositories](https://github.com/search?q=user%3Ajagi+meteor-astronomy) so you will be notified about new issues. I will be adding new issues with `discussion` label, to talk about new features and how to implement them the way developers want it to be.

Regards :)
