### ISSUE TITLE
Validation error message in nested class not work

### ISSUE THREAD

**Issue by RWizard** [jagi/meteor-astronomy#518]
Nested class

```
export const Participant = Class.create({
  name: 'Participant',
  fields: {
    firstName: {
      type: String,
      validators: [
        {
          type: 'required',
          message: 'Это обязательное поле.'
        }
      ]
    },
...
```

Error object after validate:

```
Array[2]
0
:
Object
className
:
"Participant"
message
:
""participant.firstName" is required"
name
:
"participant.firstName"
nestedName
:
"firstName"
param
:
undefined
type
:
"required"
value
:
undefined
```

Standard message about require field:
**_""participant.firstName" is required"**_
Correct message: 
**_'Это обязательное поле.'**_

Would you like resolve the problem.

**Comment by lukejagodzinski** [comment]
The problem is not in nested class but in required field. When a field is required and in your case it is, but not because of adding the `required` validator but because of lack of the `optional` property in the field's definition. In such situation Astronomy adds `required` validator with the default message. To control error message generation you have to "resolve" it on the class level not on the field level. It's all described in [documentation](http://jagi.github.io/meteor-astronomy/v2#generating-errors).

In your case nested class definition should look like that:

``` js
export const Participant = Class.create({
  name: 'Participant',
  fields: {
    firstName: {
      type: String
    }
  },
  resolveError({nestedName, validator}) {
    if (nestedName === 'firstName' && validator === 'required') {
      return 'Это обязательное поле.';
    }
  }
});
```

In fact it's much better to provide i18n error messages in the `resolveError` function as it's one place to control all messages. That way you can easily use some tools for i18n. You can for example compose key for i18n in the following way:

``` js
const i18n = {
  messages: {
    'firstName-required': 'Это обязательное поле.'
  },
  get(key) {
    return this.messages[key];
  }
};

export const Participant = Class.create({
  name: 'Participant',
  fields: {
    firstName: {
      type: String
    }
  },
  resolveError({nestedName, validator}) {
    return i18n.get(`${nestedName}-${validator}`);
  }
});
```

**Comment by RWizard** [comment]
It`s fine, thanks!
