### ISSUE TITLE
Default casting for blank strings

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#537]
A suggestion,

An empty date field has a value "", so does a number field. Currently, saving a for data gives an error due to such blank inputs. Ideally it should be treated as `null`, I think.

Date -> null, always
Number, "" -> null or 0, depending on the field is optional or not.
Boolean "" -> null or false

Does it make sense, or am I missing something?

**Comment by lukejagodzinski** [comment]
Hmm, probably that would be a good behavior. It should only work for empty strings and for non string types. I will prepare such a fix.

**Comment by lukejagodzinski** [comment]
There is a problem when checking if a field is optional in list fields like: `[Number]`, `[Date]`, `[Boolean]`. Let's take for example following fields:

``` js
required: {
  type: [Number],
  default() {
    return [];
  }
},
optional: {
  type: [Number],
  optional: true,
  default() {
    return [];
  }
}
```

Now when we set these fields to:

``` js
var i = new Item();
i.set({
  required: [''],
  optional: ['']
}, {cast: true});
console.log(i.required, i.optional); // Will print: [0] [null]
```

Which probably is ok in most cases because the `optional` field will throw an error on validation, because all elements of array have to be numbers. What do you think?

I just wonder if the `optional` option should affect elements or only entire field.

**Comment by s7dhansh** [comment]
I think `optional` should not affect the elements.
I also think that since the input field for optional array will always contain "" even in case of no input, it should actually become `null` instead of `[0] or [null]`. What say?
So, they should be cast as - `[0], null`, unless someone specified the elements to be optional too.

**Comment by lukejagodzinski** [comment]
When it would be `[0]`, `null` then it would be inconsistent, because `[0]` affects element and `null` does not affect element.

Ok will demonstrate here how different options might work for the field of the `[Number]` type:
- affecting elements:
  - required: `[0]` - will NOT throw validation error
  - optional: `[null]` - will throw validation error
- NOT affecting elements:
  - required: `""` - will throw validation error
  - optional: `null` - will NOT throw validation error

There can be only choice between affecting and non-affecting elements. I'm also for non-affecting. I won't introduce mixed version because it would confuse developers and moreover it would introduce mess in code.

**Comment by s7dhansh** [comment]
Hmm. Ok. Yes, the non-affecting one seems better.

**Comment by lukejagodzinski** [comment]
Ok good :). We should definitely treat `[Number]`, `Post`, `Number`, `Boolean` etc. as equivalent types.

**Comment by lukejagodzinski** [comment]
Sorry I mixed two different situations. There is a difference between setting `""` to the `[Number]` type field and setting `[""]`. So I'm updating demonstration here:
- setting `""` to the `[Number]` type field:
  - required: `""` - will throw validation error
  - optional: `null` - will NOT throw validation error
- setting `[""]` to the `[Number]` type field:
  - required: `[""]` - will throw validation error
  - optional: `[null]` - will throw validation error

We can't change behavior for setting `[""]` because it would stop casting values like: `["123", "321"]`. It wouldn't cast it to `[123, 321]`. I don't think it's a big problem. You would still in most cases handle adding elements to arrays by hand. Moreover you can always write your custom casting function for arrays if you want to perform some different operation. So it's very flexible.
