### ISSUE TITLE
Support for observechanges?

### ISSUE THREAD

**Issue by panphora** [jagi/meteor-astronomy#55]
I understand that meteor-astronomy uses the `transform` function to create classes and add methods, but some libraries (e.g. https://github.com/alethes/meteor-pages) use `cursor.observechanges` instead of `cursor.find`, so the transform function is never called. Is there a plan to patch this? 

I would love to be able to use model methods from astronomy on my paginated pages.

**Comment by jagi** [comment]
Hmm in `cursor.observe` it's not a problem because it returns an entire document and from what I know it uses the `transform` function. However in `cursor.observeChanged` it's in deed an issue. For now what I can suggest is trying to create a class instance by your self in the callback function:

```js
cursor.observeChanges({
  changed: function(id, fields) {
    var doc = new Post(fields);
    if (doc.validate('someField')) {
      doc.save();
    }
  }
});
```

It will be possible (in coming version) to validate multiple fields at once using the `doc.validate(['fieldA', 'fieldB'])` syntax. There are many changes to come in the next release. However, I will also add your issue to the list of the problems to fix. I will try to figure out some way of attaching into the process of changes observation.

**Comment by jagi** [comment]
Astronomy will not support `observerChanges` as there is no easy way of doing this.
