### ISSUE TITLE
Model.update $inc operator converts to a $set operation.

### ISSUE THREAD

**Issue by Andrew1431** [jagi/meteor-astronomy#556]
Hey Jagi!

I've discovered a bug in your code where passing in an $inc operator will end up being converted to a $set operation to the new value. ($inc { points: 5 } on a user whos points are 100 will become $set { points: 105 })

I discovered this when digging into a bug where a model would occasionally lose track of the number it should be if update is being called from different connections at relatively similar times. I would obtain for example 100 points from one user twice around the same time from two other users. Each of those users would get their 100 points, but the user would only go down 100 points, due to each update operation fetching the original record, modifying it, and 'setting' the new value. Upon switching the method to Model.getCollection().update I suddenly can achieve atomicity in my point adjustments. 

Thoughts?

**Comment by jagi** [comment]
Code example please.

**Comment by lukejagodzinski** [comment]
Astronomy is not performing $inc operations the way you would think. It always applies all modifiers using Meteor's utility function and later it performs before and after documents comparison. Later all changes are mostly done through the $set modifier. Such optimisation had to be done to allow more flexibility with modifying documents. If you want to be sure that the $inc operator is used then you should perform Collection.update instead of Class.update.

**Comment by thomas-p-wilson** [comment]
So...avoid Astro if we need operators to behave as expected?

**Comment by lukejagodzinski** [comment]
:) Just for methods where you care about given modifier to be actually used.

```js
var post = Post.findOne();
post.commentsCount; // 5
```

```js
Post.update(post._id, {$inc: 1});
// Will execute $set: {commentsCount: 5} modifier
```

```js
Posts.update(post._id, {$inc: 1});
// Will execute $inc: {commentsCount: 1} modifier
```

Maybe in the future release I will try to solve this problem. But it's not so easy to do.

**Comment by Andrew1431** [comment]
This completely obliterates what little atomicity mongodb has. Why can't
you pass the same args through to the underlying method.

**Comment by lukejagodzinski** [comment]
Because as I said it would require a lot of work to implement it for all possible modifiers. Moreover, for `Class.update` I've used already implemented modifications detection mechanism which only uses $set and $unset modifiers.

**Comment by lukejagodzinski** [comment]
I've improved modifications detection in 2.3.9 to include $inc and $push modifiers, however it's just temporary fix. However it will properly detect $inc and $push modifiers, when used. I will try to implement it for all modifiers in a way how MongoDB work. However it's not so easy. Validation is a piece of cake but casting has to apply to all possible modifiers so that's why I didn't use "simplest" approach (`Why can't
you pass the same args through to the underlying method.`)
