### ISSUE TITLE
Is Astronomy not using normal database operations and therefore is not working with ongoworks:security?

### ISSUE THREAD

**Issue by peXed** [jagi/meteor-astronomy#597]
Hello!

I'm currently developming a new project and I want to use Astronomy again. Now my question, is astronomy not using the normal database operations?
It seems rules, implemented by the package ongoworks:security are not going to get taken into account.

For example, I have the following rule:
Meteor.users.permit(['update', 'remove']).ifHasRole(['admin', 'edit-users']).allowInClientCode();

So only users with the correct role can perform update or remove actions in the users collection.

But it seems Astronomy is working around that rule and everybody can update or remove users.
Any solution for this or do I have to implement the security logic into the model itself without the ongoworks:security package?

Thank you!

**Comment by lukejagodzinski** [comment]
It won't work with it because the `ongoworks:security` package works on allow/deny rules and those only apply to code being executed from the client and Astronomy uses its own validation mechanism.

Moreover it's not recommended to use allow/deny rules. You should use Meteor methods everywhere it is possible

**Comment by peXed** [comment]
Ah, that was what I thought.

I will secure the app as you did it in the docs.

Thank you very much!
