### ISSUE TITLE
Validate a document in React Native

### ISSUE THREAD

**Issue by PolGuixe** [jagi/meteor-astronomy#607]
Has anybody found a way of using the validation defined in AstroClass in the React Native?

**Comment by lukejagodzinski** [comment]
Astronomy is tightly integrated with Meteor. So it might be quite difficult to use only validation. However, it's heavily modularized so in theory it's possible to strip it of the modules dependent on Meteor. In near future I will probably prepare npm Astronomy version to work with GraphQL. But it's a plan for now.

**Comment by krizka** [comment]
@lukejagodzinski How about the paln to partially move Astronomy to npm and leave only Meteor dependent parts in meteor package? I could/want help with this.

**Comment by lukejagodzinski** [comment]
So far haven't moved with it far. I'm still trying to figure out what part
of astronomy I want to focus on when moving to npm. Schema validation or
database operations or both. In both cases I want it to work with GraphQL
but also other data layers. So I have to do more project in GQL to realize
what's the good thing. When I started working on Astronomy it was just
because I was solbing a problem with lack of the good model layer for
Meteor. So far, when I work with GQL there is a little need for tool like
Astronomy but myabe that's because all projects that I work on are not
super big
