### ISSUE TITLE
class.save() is slow? (5ms)

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#614]
I'm doing an update of a bunch of records (via `forEach`), and the save() step appears to be taking about 5ms. Is that normal? There are other things going on that could be causing this (collection hooks), but I wanted to start here and see if it's something you've run into or have recommendations on.

**Comment by lukejagodzinski** [comment]
Each time you call `save()` method it has to fetch given document form database to compare it with the current values in doc. So that's why it takes some time. I could probably cache this values but that has some downsides. I did it because of the problem with some events. Such tools like Astronomy always introduce some performance issues so if you really care about performance you shouldn't use it to in such cases. However, I will investigate today possibility of introducing caching.

**Comment by JulianKingman** [comment]
This particular script is running just on the server, it seems like there should be a way to optimize server-only code. 
Does a find query take that long? Where does it actually get expensive?
- calling the method
- running event hooks
- validation
- finding/comparing 
- other?

**Comment by lukejagodzinski** [comment]
Hey, I've made an update to Astronomy (take a look at 2.4.4 release). When you're doing `Class.update` it will batch some DB operations and it will be significantly faster than doing forEach save. It's not recommended to do such an operation because it has to hit the database for each iteration.
