### ISSUE TITLE
lodash takes a lot of space in production bundle

### ISSUE THREAD

**Issue by Deadly0** [jagi/meteor-astronomy#622]
http://take.ms/bxV7P
Full lodash takes 71kb in the bundle. I guess you can import certain functions you are using in astronomy from NPM https://www.npmjs.com/search?q=lodash&page=1&ranking=optimal

Thank you for your job!

**Comment by lukejagodzinski** [comment]
Yes, I know that. I've been planning to decrease Astronomy size by using `import get from 'lodash/get'` and similar. There is no need to import separate packages. But there are around 120 files with lodash imports so it's a lot of refactoring. But I will take time to do so.

**Comment by Deadly0** [comment]
@jagi Thank you!

**Comment by lukejagodzinski** [comment]
I've been able to decrease sizes but not a lot:
`lodash`: from **71.3 kB** to **45.7 kB**
`Astronomy`: from **192 kB** to **169 kB**
I'm using `lodash` extensively so it's hard to limit bundle size by omitting not used functions.

I will publish a new version in a moment.

**Comment by lukejagodzinski** [comment]
I've release v2.4.5

I could probably not use `lodash` at all but it would require a lot of rewriting. Maybe in the future.

**Comment by jadus** [comment]
Hi, I use lodash in my meteor app. Is there a way to bundle it just once ? For now I have it once in my node modules and once in astronomy's node modules.

**Comment by lukejagodzinski** [comment]
@jadus I'm not sure about that but it used to include only one version of a package in previous Meteor releases but something might be changed from that time as recently I was able to use two versions of React in one project.

What you can do to check it out is use the same style of imports as I used in Astronomy. So instead of including it like `import _ from "lodash";` or `import { isString } from "lodash";` use `import _isString from "lodash/isString";` instead. That way Meteor should be able to detect that both imports are the same and should not included them twice.

**Comment by jadus** [comment]
Perfect ! Thanks a lot.
