### ISSUE TITLE
Should saving an invalid field to a model throw an error?

### ISSUE THREAD

**Issue by hellogerard** [jagi/meteor-astronomy#63]
Hello, great package here. This might finally be the Meteor ORM I've been looking for.

I keep running into one problem over-and-over, however.

If I attempt to save a new field to a model that has not been defined in the schema, Astronomy silently ignores the field. I keep forgetting to add new fields to the schema, resulting in errors, and wasting lots of time before realizing my error. 

Conversely, if there is a field in the database that is not defined, when I retrieve the record, the field is silently ignored, and missing from my results. 

Should Astronomy throw an error or warning in these cases for development purposes?

**Comment by jagi** [comment]
Hi, thanks.

Ok, so you are talking about two use cases. The first one is inserting a new document with extra field that is not defined in the schema and the second one retrieving document from the collection with more fields than defined in the schema.

First I will explain why I did that. I just can't save entire document as a whole because it can contain some extra properties that are used internally. Like for example validation errors list. So on insert I have to limit the amount of fields that gets saved. And in fact it would be hard to detect that there are any extra fields. It would be possible to detect them when set using the `set` method. In such situation I can print warning to the console and I think it may be good idea.

If it goes about retrieving documents from a collection it should work out of the box if the first one is implemented. Because all fields are set using the `set` method.

Would you be happy if I implement warnings? Or would you expect some other behavior?

**Comment by jagi** [comment]
I've added warnings on setting not defined fields. It will be available in the next Astronomy release. For now I'm closing this issue.

**Comment by hellogerard** [comment]
Thanks! I think this works well.
