### ISSUE TITLE
Relation module and subscriptions

### ISSUE THREAD

**Issue by chroz** [jagi/meteor-astronomy#64]
Hi there! Thanks for these great package(s), just what I've been looking for :)

In order for the relations to work, all relevant data must of course be published ( and subscribed to ).

When I setup my subscriptions I usually have to query on a foreign key, after first retrieving an initial document. (for example fetch a post, then fetch its comments by post_id) I generally don't want to fetch all comments. I suppose this is more of a general Meteor question/ problem.

However, I was wondering if you had had any thoughts on some strategy where one could also use the defined Astronomy relations for also getting some set of subscriptions for use in iron-router and/or templates? Would it be hard to do, (or a bad idea?)

**Comment by jagi** [comment]
Hi, thanks :)

Yes, it's definitely something worth implementing that I was thinking about. There is a package called publish-with-relations or something like this that I was using in my projects. I was planning to integrate it into Astronomy so that application would subscribe to all necessary publications. However, right now I have a lot of work to do regarding the next version of astronomy. So, it will take time to implement this feature. Of course you can do it manually using publish-with-relations package.

**Comment by chroz** [comment]
Ok, thanks for the tip!

**Comment by jagi** [comment]
I'm closing this issue. I've prepared a [list of feature requests](https://github.com/jagi/meteor-astronomy/wiki/Feature-Requests) that will appear in Astronomy 1.0 and Astronomy 2.0. Some of them are already being developed. Other will appear in near future in 1.0 or 2.0 version. I will be updating this list. I will probably have to create some tool for voting on features to implement.
