### ISSUE TITLE
Ability to validate multiple specified fields at the same time

### ISSUE THREAD

**Issue by MichaelOber** [jagi/meteor-astronomy#65]
Right now, you have three options:

post.validateAll() to validate all fields. Error messages are for all fields
post.validate() to validate all fields, stopping at the first error. Error Message is for first field only.
post.validate('name') to validate a single field. Error message is only for specified field.

Would it be possible to add something like
post.validate('name', 'date') to validate both and only those fields, and getting error messages for both? Doing something like `if (post.validate('name') && post.validate('date'))` won't work because if the first field fails, the second won't be validated.

An example use case for this would be for a User object where the application would have several forms for different parts of the object, such as settings, preferences, etc. It would be nice to have a single User class while being able to control what gets validated.

Please correct me if there is currently a way to do this that I am just ignorant of.

Thank you.

Mike

**Comment by jagi** [comment]
Hi, thanks for this issue. Actually it was already implemented in the newest version :) which is not published yet. You will be able to do:

```js
user.validate(['name', 'date']);
```

It will take some time to publish it because it bigger update that changes a lot in Astronomy. So stay tuned :). For now I can recommend some workaround:

```js
var validateMultiple = function(doc, fields) {
  return _.every(fields, function(field) {
    return doc.validate(field);
  });
};

// Usage
var user = new User();
validateMultiple(user, ['name', 'date']);
```

It should work. And when the new version is released, you will be able to use previously mentioned solution :).

**Comment by jagi** [comment]
For now I'm closing this issue because the feature is implemented and will appear in the next release.
