### ISSUE TITLE
async/await and Promises Meteor Methods

### ISSUE THREAD

**Issue by davidsavoie1** [jagi/meteor-astronomy#661]
Hi again! This one is more for general information...

I'm writing some of my Meteor code with async/await instead of callbacks where it makes sense and I must use [`didericis:callpromise-mixin`](https://atmospherejs.com/didericis/callpromise-mixin) to integrate with [`mdg:validated-method`](https://github.com/meteor/validated-method) and call them with `callPromise`. I thought for a while that I could somehow write my `MeteorMethods` in Astronomy in an async/await or Promise returning style, but after struggling quite a bit trying to understand why my errors weren't handled properly, I realized that maybe Astronomy itself could not handle such patterns.

**Is there a way to write Promise returning `MeteorMethods` inside Astronomy?** Only returning a Promise doesn't seem to work properly if I need to `await` for a server-only code to return, no matter what I try...

Thanks a lot!

**Comment by lukejagodzinski** [comment]
I've never used these packages. Please, show some code where you're trying to implement such a method, then maybe I will be able to help.

**Comment by lukejagodzinski** [comment]
I've made a simple test of async/await with Astronomy Meteor methods. I've added the `test` meteor method to my `User` class from the `meteor-astronomy-example` repository:

```js
  meteorMethods: {
    async test() {
      return await new Promise(resolve => {
        setTimeout(() => {
          resolve(`The "test" method result`);
        }, 1000);
      });
    },
  }
```

Now having this method I'm invoking it from the browser console in the following way:

```js
(async function() {
  var user = User.findOne();
  console.log(await user.test());
})();
```

And after 1 second I get the `The "test" method result` message. So async/await works properly with Astronomy Meteor methods. When a method is `async` then it will always return a promise and you can await such a method call.

Don't know exactly what your problem is and if this explanation is any help for you.

**Comment by davidsavoie1** [comment]
Hi @lukejagodzinski! Sorry I'm responding late... I had been using async with Astronomy in the past as you described, but the problem I got this time was with a somewhat more complicated pattern. Since I could do without `async`/`await`, I didn't dig into it more for now and went back using callbacks for now. So I'll close this one.

Thanks a lot for your help!
