### ISSUE TITLE
function as default value

### ISSUE THREAD

**Issue by mmintel** [jagi/meteor-astronomy#72]
Hi there,
I am just coming from SimpleSchema and want to translate my schemas to astronomy.
I didn't find the right place in your documentation.. I want to add the current users id to the owner field of my schema which worked like this in SimpleSchema:

```
owner: {
    type: String,
    default:function(){ return this.userId }
}
```

Is that possible with astronomy? Do I have to register an event for that?

Cheers
Marc

**Comment by jagi** [comment]
Hi, yes right now you have to use the `beforeInsert` event. However, it's good idea to implement such feature. I will add it in the next release.

**Comment by mmintel** [comment]
I see you are not lazy Mr.Myjagi! :+1:

**Comment by jagi** [comment]
Feature has been implemented and will appear in the next release. It's getting closer to this moment. So stay tuned :). For now I'm closing this issue.

**Comment by cjsauer** [comment]
I don't understand how to use the `beforeInsert` event to achieve this. If I want to capture the userId into a field before insert, I imagine it would look like this: 

```javascript
...
events: {                                                                                         
    'beforeInsert': function(e) {                                                                              
      this.set('creatorId', Meteor.userId());                                   
  },
...
```

But this error appears: `Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.`

How would I achieve this using the Event system in Astronomy?

**Comment by jagi** [comment]
You should create a new issue for this question, however I will answer your it here.

If you are using `Meteor.userId()` you should be aware of the context in which you have to invoke it. As the error states you should call it in the Meteor method. As the `beforeInsert` event gets called when invoking the `save()` method, so you should put the code `doc.save()` in a method.

```js
Meteor.methods({
  '/doc/save': function(doc) {
    doc.save();
  }
});
```

And call method:

```js
var doc = new Doc();
Meteor.call('/doc/save', doc);
```

There's not other way around to save it and get `userId`. You can't just write the `doc.save()` on the client and use allow/deny rules if you are using `Meteor.userId()`. It's not something Astronomy specific, it's how it works in Meteor.

I've read somewhere a discussion of MDG with developers about removing allow/deny rules from Meteor and force users to create methods instead. In fact allow/deny rules and `Collection.insert()` etc. functions are using Meteor methods to perform an action. However, not many developers are aware of that.

You can also read many articles about not using allow/deny rules because they are not reliable and can cause many hidden security holes. I would encourage you to avoid using them.
