### ISSUE TITLE
Calling server method from client

### ISSUE THREAD

**Issue by tdamsma** [jagi/meteor-astronomy#76]
How can I add a method to a class that runs on the server, but is called from the browser? 
For example: I have a class users and posts, and I want to return the count for the number of posts per user. So I add the method as follows:

    methods: 
      countPosts: -> Posts.find({userId: this._id}).count()

On the server this returns the correct result but on the client, I am only subscribed to a subset of the posts, so the result is not correct. How can I get the correct count for this method on the client?

**Comment by jagi** [comment]
Hi, it will be something like this:

```js
// Client & Server
Item = Astro.Class({
  /* ... */
  collection: Items,
  methods: {
    countPost: function() {
      return Posts.find({
        userId: this._id
      }).count();
    }
  }
});

// Server
Meteor.methods({
  getPostsCount: function(postId) {
    // Do security check here. Are you sure that given user should have access to this method? Etc.
    var item = Items.findOne(postId);
    return item.countPost();
  }
});

// Client
Meteor.call('getPostsCount', item._id, function(err, postsCount) {
  // Do something with "postsCount"
});
```

It's not perfect but if you are not subscribed to all the documents it's probably the only way. You have to call server method from the client and wait for value returned from the server.

**Comment by tdamsma** [comment]
Thanks for the quick reply! Too bad I can't keep the code with the class definition. Do you see a way to abstract this away? Would be cool if I could just add a serverMethod to my class and that all this is then taken care of. But I think you have enough stuff to add already. Looking forward to the next release, keep up the good work!

**Comment by jagi** [comment]
It would be possible to add such methods to the class but it would be hard to implement. There are a lot of variables.

It could look as follows:
- Every class method would be also registered as a Meteor method. In fact `Collection.insert` is just a method `Meteor.call('/collection/insert')`.
- Calling class method would call Meteor method that was registered.
```js
item.countPost();
// is translated to...
Meteor.call('/item/countPosts', item._id);
```
- The `countPost` method is run on both client and server.
- The simulated method (on the client) in your case would return incorrect value because you are not subscribed to all needed documents.

The problem is with received correct data from the server if client data is invalid. First of all you wouldn't be able to do just (on the client):

```js
// Client
var count = item.countPosts(); // Returns invalid value
```

You would have to somehow receive response from the server. The solution would be callback or promise.

```js
// Client
item.countPosts(function(count) { // Has to wait for server response
  // do something with the "count"
});
```

There are a lot of problems with such solution. It's not ideal. Maybe instead messing with current methods, I could implement something like `serverMethods` that always get called on the server and you have to wait for the response.

```js
Item = Astro.Class({
  /* ... */
  methods: {
    getName: function() {}
  },
  serverMethods: {
    countPosts: function() {
      return /*calculate posts count and return */;
    }
  }
});

// Usage

item.countPosts(function(count) {
  // Do something with the "count"
});
```

I can add it for consideration in the future releases

**Comment by banglashi** [comment]
Hi @tdamsma,
in the meantime you can use a package like tmeasday:publish-counts to publish the count of documents with your subscription.

**Comment by jagi** [comment]
Right now I'm not going to implement this feature. If there will be a demand I will implement it in the Astronomy 2.0.
