### ISSUE TITLE
Clarity on how it plays with Allow/Deny?

### ISSUE THREAD

**Issue by ashokgelal** [jagi/meteor-astronomy#78]
Sorry if this is a stupid question, but how does Astronomy play with Allow/Deny? Does it ignore them completely? There is no mention of allow/deny anywhere. It'd be nice to have some documentation on how to securely use Astronomy.

**Comment by ashokgelal** [comment]
Just stumbled upon this: https://forums.meteor.com/t/astronomy-package-as-a-model-layer-for-meteor-questions-pros-cons/6812 :+1: 

It'd still be nice to have some documentation here on GitHub probably with a nice example. I'd do but I'm not yet too familiar with Meteor security as well as Astronomy :(

**Comment by jagi** [comment]
While working on the next Astronomy release, in the meantime I'm also working on better documentation. It will be much more detailed. The "security" section is definitely "must have". There are some parts in Astronomy that helps with security like the fields definition or validation. However, you have to make sure that everything is secure by yourself using standard Meteor security features.

There are two ways:
- Allow / deny rules
- Meteor methods (not Astronom methods)

In my opinion relaying on the allow / deny rules is a bad idea. The rules are called only on the SERVER and only when on the CLIENT the `insert`, `upsert`, `update` or `remove` methods are called directly on the collection. In fact those calls are translated into Meteor methods.

- `var Posts = new Mongo.Collection('posts');`
- `Posts.insert(data);` translates to `Meteor.call('/posts/insert`, data);`
- The allow / deny rules are run for the insert operation

Is see Meteor methods the better way of managing security. However, I don't want to get into details right now because I will describe everything in the security section of the documentation.

If you are new to Meteor's security system, I would recommend reading documentation first and watching some video tutorial. The "Discover Meteor" book is also a good choice. I would also recommend [EventedMind](https://www.eventedmind.com/) website which is great source of knowledge about Meteor internals.

**Comment by ashokgelal** [comment]
I've read Discover Meteor book (twice) and watched some of EventedMind videos as well. I wasn't just sure how Astronomy fitted with the security model. I'm pretty sure I've more readings to do. Thanks for the answer and thanks for this great library.

**Comment by jagi** [comment]
No problem :-). I think that when I update documentation with some good tutorials everything will be clear :-)
