### ISSUE TITLE
default value as function

### ISSUE THREAD

**Issue by dandv** [jagi/meteor-astronomy#81]
Is it possible to define default values as functions (which wound return a value computed based on other fields and/or data, such as the current date)? The examples only list constants such as null or the empty string.

**Comment by jagi** [comment]
Yes, it's possible in the new version that will be release soon. However the context of the function is not set to document. Maybe I will change it.

```js
fields: {
  age: {
    type: 'string',
    default: function() {
      this; // Window object
      return (new Date()).getFullYear() - this.get('birthDate').getFullYear()); // Would be nice to have
    }
  }
}
```

However there are some problems with setting default value based on the other field's value. Because you can't assume that other's field value had already been set.

**Comment by dandv** [comment]
> However there are some problems with setting default value based on the other field's value. Because you can't assume that other's field value had already been set.

Related to #80 then.

Would it be safe to assume that other fields have been set in [`afterset`](https://github.com/jagi/meteor-astronomy#field-events)?

**Comment by jagi** [comment]
The process of constructing document looks like follows (in the new version):
- Create an empty document
- Loop through all fields and set a default value for each one
- Set values passed to constructor `new Item(values);`
  - Loop through values and set each value
  - Call the `beforeSet` event, set value, call the `afterSet` event

So, as you see the order of fields that are being set determines if the other values was set before or after another one.

However there are two event in the new release `beforeInit` and `afterInit`. As the names say, the first one is invoked at the beginning before setting default values and the second one is execute after setting all values. So it's a good place to set value that depends on the other field's value.

**Comment by jagi** [comment]
Now it's possible to pass a function as a default value that will be executed on a document creation. It was possible to set the context of this function to the document. I've tested and it worked but there was no reason for having it, because as we talked you can relay on other fields' values. You should use the `afterInit` event for that purpose, which will also appear in the next release.

For now, I'm closing this issue.
