### ISSUE TITLE
Enum type

### ISSUE THREAD

**Issue by Deadly0** [jagi/meteor-astronomy#98]
Hi @jagi, thank you for 1.0 update, it's looks nice!

How about to add something like `enum` type to default types?

```
myEnum: {
      type: 'enum',
      values: ['OPENED', 'NEW', 'CLOSED'],
      default: 'NEW'
}
```

**Comment by davidystephenson** [comment]
This would be greatly appreciated. Perhaps it could be a generic field property like default.

**Comment by jagi** [comment]
Sorry I missed it when checking issues. It may be good feature to implement in future releases. I will try incorporating it. For now you can achieve it using validators and default value. You have to use the`choice` validator and pass all possible values.

The feature you're proposing is very interesting to consider. I have one idea for improvement in Meteor that would probably solve problem with many databases support. And enum type exists in SQL databases but not in MongoDB. That's why database abstraction is needed in such situations. You may think that I'm talking right now about something not related with your feature :-). However when implement any feature I'm trying to predict what problem I can have in the future. And I want to implement support for other databases.

So as I said I will consider it, but I don't think that it will appear soon. But it's something that definitely should be done.

**Comment by davidystephenson** [comment]
@jagi I'm not sure how helpful this is, but mongoose does have this functionality: http://mongoosejs.com/docs/api.html#schema_string_SchemaString-enum

**Comment by jagi** [comment]
@davidystephenson Implementing it isn't something difficult. I just always think about database abstraction when implementing some feature. In SQL it's just field type but that you be one to one compatible feature. In MongoDB this type would have to be implemented in JS, because MongoDB doesn't care about types. Moreover, right now types in Astronomy does not take any parameters, I mean types like `string`, `number` etc. I made special types `array` and `object` that are MongoDB specific. They can take params. I could make it the same way if it goes about the `enum` type, but when I think about it more it can get a little bit messy. Right now I've made some compromises to allow nested fields in Astronomy and enum type would be a next compromise to make. I don't want to make such decision under presser :). It just needs time. Let me just release 1.0.0 first and after that we will think about improvements :)

**Comment by jagi** [comment]
I'm closing this issue. I've prepared a [list of feature requests](https://github.com/jagi/meteor-astronomy/wiki/Feature-Requests) that will appear in Astronomy 1.0 and Astronomy 2.0. Some of them are already being developed. Other will appear in near future in 1.0 or 2.0 version. I will be updating this list. I will probably have to create some tool for voting on features to implement.

**Comment by molinto** [comment]
Sorry, isn't this the same as ENUM?:
```
// Example:
validators: {
  sex: Validators.choice(['male', 'female'])
}
```

**Comment by jagi** [comment]
Yes it would be the same with this difference that the `sex` field is able to store any value and only throws error on validation. The `ENUM` type is intended to avoid setting value that is not from the list.
